version: "3.9"


services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./backend/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    profiles: ["debug"]         # 可选调试UI
    restart: unless-stopped
    environment:
      HTTP_PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - mqtt

  home-gateway:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: pc-remote/home-gateway:local
    restart: unless-stopped
    depends_on:
      - mqtt
    environment:
      LOCAL_PORT: "7071"
      MQTT_URL: tcp://mqtt:1883
      HOME_DEVICES_DB: /data/home.db
      HOME_DEVICES_FILE: /data/home.db
      HOME_SCENES_FILE: /data/scenes.json
      HOME_AUTOMATIONS_FILE: /data/automations.json
          # 云端 cloud-middleware 的外部可达地址（给 agent 连接用）
      CLOUD_ADDR: "${CLOUD_ADDR}"

      # 这个家庭网关的唯一 ID（你自己定义，但 cloud 会用它来识别“哪一户”）
      AGENT_DEVICE_ID: "${AGENT_DEVICE_ID}"

      # 如果 cloud-middleware 需要共享密钥，这里要匹配；cloud 现在 AUTH_MODE=none，就可以留空
      AGENT_SECRET: "${AGENT_SECRET}"
      HOME_GRPC_ADDR: "${HOME_GRPC_ADDR}"
    volumes:
      - ./backend/data:/data
    ports:
      - "7071:7071"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_HOME_GRPCWEB_URL: /api
        VITE_CLOUD_GRPCWEB_URL: /cloud
    image: pc-remote/frontend:local
    profiles: ["local-ui"]      # ← 可选本地前端
    restart: unless-stopped
    environment:
      HOME_BACKEND_URL: http://home-gateway:7071/
      CLOUD_GATEWAY_URL: ""
    depends_on:
      - home-gateway
    ports:
      - "8080:80"

volumes:
  mosquitto-data:
  mosquitto-log: