// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: remote_control.proto

package controllerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerService_ExecuteCommandSet_FullMethodName = "/remote_control.ControllerService/ExecuteCommandSet"
	ControllerService_StoreCommandSet_FullMethodName   = "/remote_control.ControllerService/StoreCommandSet"
	ControllerService_GetAllCommandSets_FullMethodName = "/remote_control.ControllerService/GetAllCommandSets"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 控制器服务 - 统一基于命令集概念
type ControllerServiceClient interface {
	// 执行命令集
	ExecuteCommandSet(ctx context.Context, in *ExecuteCommandSetRequest, opts ...grpc.CallOption) (*ExecuteCommandSetResponse, error)
	// 存储命令集
	StoreCommandSet(ctx context.Context, in *StoreCommandSetRequest, opts ...grpc.CallOption) (*StoreCommandSetResponse, error)
	// 获取全部命令集
	GetAllCommandSets(ctx context.Context, in *GetAllCommandSetsRequest, opts ...grpc.CallOption) (*GetAllCommandSetsResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) ExecuteCommandSet(ctx context.Context, in *ExecuteCommandSetRequest, opts ...grpc.CallOption) (*ExecuteCommandSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandSetResponse)
	err := c.cc.Invoke(ctx, ControllerService_ExecuteCommandSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) StoreCommandSet(ctx context.Context, in *StoreCommandSetRequest, opts ...grpc.CallOption) (*StoreCommandSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreCommandSetResponse)
	err := c.cc.Invoke(ctx, ControllerService_StoreCommandSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetAllCommandSets(ctx context.Context, in *GetAllCommandSetsRequest, opts ...grpc.CallOption) (*GetAllCommandSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCommandSetsResponse)
	err := c.cc.Invoke(ctx, ControllerService_GetAllCommandSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
//
// 控制器服务 - 统一基于命令集概念
type ControllerServiceServer interface {
	// 执行命令集
	ExecuteCommandSet(context.Context, *ExecuteCommandSetRequest) (*ExecuteCommandSetResponse, error)
	// 存储命令集
	StoreCommandSet(context.Context, *StoreCommandSetRequest) (*StoreCommandSetResponse, error)
	// 获取全部命令集
	GetAllCommandSets(context.Context, *GetAllCommandSetsRequest) (*GetAllCommandSetsResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) ExecuteCommandSet(context.Context, *ExecuteCommandSetRequest) (*ExecuteCommandSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommandSet not implemented")
}
func (UnimplementedControllerServiceServer) StoreCommandSet(context.Context, *StoreCommandSetRequest) (*StoreCommandSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreCommandSet not implemented")
}
func (UnimplementedControllerServiceServer) GetAllCommandSets(context.Context, *GetAllCommandSetsRequest) (*GetAllCommandSetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCommandSets not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call pancis, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_ExecuteCommandSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ExecuteCommandSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ExecuteCommandSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ExecuteCommandSet(ctx, req.(*ExecuteCommandSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_StoreCommandSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreCommandSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).StoreCommandSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_StoreCommandSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).StoreCommandSet(ctx, req.(*StoreCommandSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetAllCommandSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCommandSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetAllCommandSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetAllCommandSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetAllCommandSets(ctx, req.(*GetAllCommandSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommandSet",
			Handler:    _ControllerService_ExecuteCommandSet_Handler,
		},
		{
			MethodName: "StoreCommandSet",
			Handler:    _ControllerService_StoreCommandSet_Handler,
		},
		{
			MethodName: "GetAllCommandSets",
			Handler:    _ControllerService_GetAllCommandSets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remote_control.proto",
}
