// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "controller.proto" (package "controller", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * 执行命令请求
 *
 * @generated from protobuf message controller.ExecuteCommandRequest
 */
export interface ExecuteCommandRequest {
    /**
     * @generated from protobuf field: string command_id = 1
     */
    commandId: string; // 命令ID
}
/**
 * 执行命令响应
 *
 * @generated from protobuf message controller.ExecuteCommandResponse
 */
export interface ExecuteCommandResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean; // 是否成功
    /**
     * @generated from protobuf field: string output = 2
     */
    output: string; // 输出内容
    /**
     * @generated from protobuf field: string error = 3
     */
    error: string; // 错误信息
    /**
     * @generated from protobuf field: int32 exit_code = 4
     */
    exitCode: number; // 退出码
}
/**
 * 存储命令请求
 *
 * @generated from protobuf message controller.StoreCommandRequest
 */
export interface StoreCommandRequest {
    /**
     * @generated from protobuf field: string command_id = 1
     */
    commandId: string; // 命令ID
    /**
     * @generated from protobuf field: string command_name = 2
     */
    commandName: string; // 命令名称
    /**
     * @generated from protobuf field: string command_script = 3
     */
    commandScript: string; // 命令脚本
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string; // 描述
}
/**
 * 存储命令响应
 *
 * @generated from protobuf message controller.StoreCommandResponse
 */
export interface StoreCommandResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * 获取全部命令请求
 *
 * 空请求
 *
 * @generated from protobuf message controller.GetAllCommandsRequest
 */
export interface GetAllCommandsRequest {
}
/**
 * 命令信息
 *
 * @generated from protobuf message controller.CommandInfo
 */
export interface CommandInfo {
    /**
     * @generated from protobuf field: string command_id = 1
     */
    commandId: string;
    /**
     * @generated from protobuf field: string command_name = 2
     */
    commandName: string;
    /**
     * @generated from protobuf field: string command_script = 3
     */
    commandScript: string;
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
}
/**
 * 获取全部命令响应
 *
 * @generated from protobuf message controller.GetAllCommandsResponse
 */
export interface GetAllCommandsResponse {
    /**
     * @generated from protobuf field: repeated controller.CommandInfo commands = 1
     */
    commands: CommandInfo[];
}
// @generated message type with reflection information, may provide speed optimized methods
class ExecuteCommandRequest$Type extends MessageType<ExecuteCommandRequest> {
    constructor() {
        super("controller.ExecuteCommandRequest", [
            { no: 1, name: "command_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ExecuteCommandRequest>): ExecuteCommandRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.commandId = "";
        if (value !== undefined)
            reflectionMergePartial<ExecuteCommandRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExecuteCommandRequest): ExecuteCommandRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string command_id */ 1:
                    message.commandId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExecuteCommandRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string command_id = 1; */
        if (message.commandId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.commandId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message controller.ExecuteCommandRequest
 */
export const ExecuteCommandRequest = new ExecuteCommandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExecuteCommandResponse$Type extends MessageType<ExecuteCommandResponse> {
    constructor() {
        super("controller.ExecuteCommandResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "output", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "exit_code", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ExecuteCommandResponse>): ExecuteCommandResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.output = "";
        message.error = "";
        message.exitCode = 0;
        if (value !== undefined)
            reflectionMergePartial<ExecuteCommandResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExecuteCommandResponse): ExecuteCommandResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string output */ 2:
                    message.output = reader.string();
                    break;
                case /* string error */ 3:
                    message.error = reader.string();
                    break;
                case /* int32 exit_code */ 4:
                    message.exitCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExecuteCommandResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string output = 2; */
        if (message.output !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.output);
        /* string error = 3; */
        if (message.error !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.error);
        /* int32 exit_code = 4; */
        if (message.exitCode !== 0)
            writer.tag(4, WireType.Varint).int32(message.exitCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message controller.ExecuteCommandResponse
 */
export const ExecuteCommandResponse = new ExecuteCommandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StoreCommandRequest$Type extends MessageType<StoreCommandRequest> {
    constructor() {
        super("controller.StoreCommandRequest", [
            { no: 1, name: "command_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "command_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "command_script", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StoreCommandRequest>): StoreCommandRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.commandId = "";
        message.commandName = "";
        message.commandScript = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<StoreCommandRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StoreCommandRequest): StoreCommandRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string command_id */ 1:
                    message.commandId = reader.string();
                    break;
                case /* string command_name */ 2:
                    message.commandName = reader.string();
                    break;
                case /* string command_script */ 3:
                    message.commandScript = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StoreCommandRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string command_id = 1; */
        if (message.commandId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.commandId);
        /* string command_name = 2; */
        if (message.commandName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.commandName);
        /* string command_script = 3; */
        if (message.commandScript !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.commandScript);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message controller.StoreCommandRequest
 */
export const StoreCommandRequest = new StoreCommandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StoreCommandResponse$Type extends MessageType<StoreCommandResponse> {
    constructor() {
        super("controller.StoreCommandResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StoreCommandResponse>): StoreCommandResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<StoreCommandResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StoreCommandResponse): StoreCommandResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StoreCommandResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message controller.StoreCommandResponse
 */
export const StoreCommandResponse = new StoreCommandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllCommandsRequest$Type extends MessageType<GetAllCommandsRequest> {
    constructor() {
        super("controller.GetAllCommandsRequest", []);
    }
    create(value?: PartialMessage<GetAllCommandsRequest>): GetAllCommandsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAllCommandsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllCommandsRequest): GetAllCommandsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllCommandsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message controller.GetAllCommandsRequest
 */
export const GetAllCommandsRequest = new GetAllCommandsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommandInfo$Type extends MessageType<CommandInfo> {
    constructor() {
        super("controller.CommandInfo", [
            { no: 1, name: "command_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "command_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "command_script", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CommandInfo>): CommandInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.commandId = "";
        message.commandName = "";
        message.commandScript = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<CommandInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommandInfo): CommandInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string command_id */ 1:
                    message.commandId = reader.string();
                    break;
                case /* string command_name */ 2:
                    message.commandName = reader.string();
                    break;
                case /* string command_script */ 3:
                    message.commandScript = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommandInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string command_id = 1; */
        if (message.commandId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.commandId);
        /* string command_name = 2; */
        if (message.commandName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.commandName);
        /* string command_script = 3; */
        if (message.commandScript !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.commandScript);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message controller.CommandInfo
 */
export const CommandInfo = new CommandInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllCommandsResponse$Type extends MessageType<GetAllCommandsResponse> {
    constructor() {
        super("controller.GetAllCommandsResponse", [
            { no: 1, name: "commands", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CommandInfo }
        ]);
    }
    create(value?: PartialMessage<GetAllCommandsResponse>): GetAllCommandsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.commands = [];
        if (value !== undefined)
            reflectionMergePartial<GetAllCommandsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllCommandsResponse): GetAllCommandsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated controller.CommandInfo commands */ 1:
                    message.commands.push(CommandInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllCommandsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated controller.CommandInfo commands = 1; */
        for (let i = 0; i < message.commands.length; i++)
            CommandInfo.internalBinaryWrite(message.commands[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message controller.GetAllCommandsResponse
 */
export const GetAllCommandsResponse = new GetAllCommandsResponse$Type();
/**
 * @generated ServiceType for protobuf service controller.ControllerService
 */
export const ControllerService = new ServiceType("controller.ControllerService", [
    { name: "ExecuteCommand", options: {}, I: ExecuteCommandRequest, O: ExecuteCommandResponse },
    { name: "StoreCommand", options: {}, I: StoreCommandRequest, O: StoreCommandResponse },
    { name: "GetAllCommands", options: {}, I: GetAllCommandsRequest, O: GetAllCommandsResponse }
]);
