// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "cloud/agent.proto" (package "remote_control.cloud.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message remote_control.cloud.v1.RegisterRequest
 */
export interface RegisterRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string; // 设备唯一ID
    /**
     * @generated from protobuf field: string home_grpc_addr = 2
     */
    homeGrpcAddr: string; // 设备侧 HomeService 可达地址，例如 10.0.0.5:7071 或公网IP:端口
    /**
     * @generated from protobuf field: string secret = 3
     */
    secret: string; // 设备注册密钥（与云端配置匹配）
    /**
     * @generated from protobuf field: repeated string tags = 4
     */
    tags: string[]; // 标签（可用于路由/过滤）
    /**
     * @generated from protobuf field: int32 ttl_sec = 5
     */
    ttlSec: number; // 注册有效期，心跳刷新
}
/**
 * @generated from protobuf message remote_control.cloud.v1.RegisterResponse
 */
export interface RegisterResponse {
    /**
     * @generated from protobuf field: bool ok = 1
     */
    ok: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message remote_control.cloud.v1.HeartbeatRequest
 */
export interface HeartbeatRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
}
/**
 * @generated from protobuf message remote_control.cloud.v1.HeartbeatResponse
 */
export interface HeartbeatResponse {
    /**
     * @generated from protobuf field: bool ok = 1
     */
    ok: boolean;
}
/**
 * @generated from protobuf message remote_control.cloud.v1.TunnelFrame
 */
export interface TunnelFrame {
    /**
     * @generated from protobuf field: string corr_id = 1
     */
    corrId: string; // 关联一次调用生命周期
    /**
     * @generated from protobuf field: remote_control.cloud.v1.FrameType type = 2
     */
    type: FrameType;
    /**
     * @generated from protobuf field: string method = 3
     */
    method: string; // 目标方法名，仅 OPEN 时填写，例如 "/remote_control.home.HomeService/InvokeAction"
    /**
     * @generated from protobuf field: bytes payload = 4
     */
    payload: Uint8Array; // 负载：请求/响应/流数据按 wire 格式承载
    /**
     * @generated from protobuf field: string message = 5
     */
    message: string; // 错误描述（ERROR 时）
}
/**
 * @generated from protobuf enum remote_control.cloud.v1.FrameType
 */
export enum FrameType {
    /**
     * @generated from protobuf enum value: FRAME_TYPE_UNSPECIFIED = 0;
     */
    FRAME_TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: OPEN = 1;
     */
    OPEN = 1,
    /**
     * @generated from protobuf enum value: DATA = 2;
     */
    DATA = 2,
    /**
     * @generated from protobuf enum value: CLOSE = 3;
     */
    CLOSE = 3,
    /**
     * @generated from protobuf enum value: ERROR = 4;
     */
    ERROR = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class RegisterRequest$Type extends MessageType<RegisterRequest> {
    constructor() {
        super("remote_control.cloud.v1.RegisterRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "home_grpc_addr", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "secret", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tags", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "ttl_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterRequest>): RegisterRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.homeGrpcAddr = "";
        message.secret = "";
        message.tags = [];
        message.ttlSec = 0;
        if (value !== undefined)
            reflectionMergePartial<RegisterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterRequest): RegisterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string home_grpc_addr */ 2:
                    message.homeGrpcAddr = reader.string();
                    break;
                case /* string secret */ 3:
                    message.secret = reader.string();
                    break;
                case /* repeated string tags */ 4:
                    message.tags.push(reader.string());
                    break;
                case /* int32 ttl_sec */ 5:
                    message.ttlSec = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string home_grpc_addr = 2; */
        if (message.homeGrpcAddr !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.homeGrpcAddr);
        /* string secret = 3; */
        if (message.secret !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.secret);
        /* repeated string tags = 4; */
        for (let i = 0; i < message.tags.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.tags[i]);
        /* int32 ttl_sec = 5; */
        if (message.ttlSec !== 0)
            writer.tag(5, WireType.Varint).int32(message.ttlSec);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.RegisterRequest
 */
export const RegisterRequest = new RegisterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterResponse$Type extends MessageType<RegisterResponse> {
    constructor() {
        super("remote_control.cloud.v1.RegisterResponse", [
            { no: 1, name: "ok", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterResponse>): RegisterResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ok = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<RegisterResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterResponse): RegisterResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool ok */ 1:
                    message.ok = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool ok = 1; */
        if (message.ok !== false)
            writer.tag(1, WireType.Varint).bool(message.ok);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.RegisterResponse
 */
export const RegisterResponse = new RegisterResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HeartbeatRequest$Type extends MessageType<HeartbeatRequest> {
    constructor() {
        super("remote_control.cloud.v1.HeartbeatRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HeartbeatRequest>): HeartbeatRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<HeartbeatRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HeartbeatRequest): HeartbeatRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HeartbeatRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.HeartbeatRequest
 */
export const HeartbeatRequest = new HeartbeatRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HeartbeatResponse$Type extends MessageType<HeartbeatResponse> {
    constructor() {
        super("remote_control.cloud.v1.HeartbeatResponse", [
            { no: 1, name: "ok", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<HeartbeatResponse>): HeartbeatResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ok = false;
        if (value !== undefined)
            reflectionMergePartial<HeartbeatResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HeartbeatResponse): HeartbeatResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool ok */ 1:
                    message.ok = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HeartbeatResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool ok = 1; */
        if (message.ok !== false)
            writer.tag(1, WireType.Varint).bool(message.ok);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.HeartbeatResponse
 */
export const HeartbeatResponse = new HeartbeatResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TunnelFrame$Type extends MessageType<TunnelFrame> {
    constructor() {
        super("remote_control.cloud.v1.TunnelFrame", [
            { no: 1, name: "corr_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["remote_control.cloud.v1.FrameType", FrameType] },
            { no: 3, name: "method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 5, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TunnelFrame>): TunnelFrame {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.corrId = "";
        message.type = 0;
        message.method = "";
        message.payload = new Uint8Array(0);
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<TunnelFrame>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TunnelFrame): TunnelFrame {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string corr_id */ 1:
                    message.corrId = reader.string();
                    break;
                case /* remote_control.cloud.v1.FrameType type */ 2:
                    message.type = reader.int32();
                    break;
                case /* string method */ 3:
                    message.method = reader.string();
                    break;
                case /* bytes payload */ 4:
                    message.payload = reader.bytes();
                    break;
                case /* string message */ 5:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TunnelFrame, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string corr_id = 1; */
        if (message.corrId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.corrId);
        /* remote_control.cloud.v1.FrameType type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        /* string method = 3; */
        if (message.method !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.method);
        /* bytes payload = 4; */
        if (message.payload.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.payload);
        /* string message = 5; */
        if (message.message !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.TunnelFrame
 */
export const TunnelFrame = new TunnelFrame$Type();
/**
 * @generated ServiceType for protobuf service remote_control.cloud.v1.AgentService
 */
export const AgentService = new ServiceType("remote_control.cloud.v1.AgentService", [
    { name: "Register", options: {}, I: RegisterRequest, O: RegisterResponse },
    { name: "Heartbeat", options: {}, I: HeartbeatRequest, O: HeartbeatResponse }
]);
/**
 * @generated ServiceType for protobuf service remote_control.cloud.v1.TunnelService
 */
export const TunnelService = new ServiceType("remote_control.cloud.v1.TunnelService", [
    { name: "Open", serverStreaming: true, clientStreaming: true, options: {}, I: TunnelFrame, O: TunnelFrame }
]);
