// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "cloud/device.proto" (package "remote_control.cloud.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DeviceRegistryService } from "./device";
import type { LogAck } from "./device";
import type { LogLine } from "./device";
import type { CloudMessage } from "./device";
import type { AgentMessage } from "./device";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListDevicesResponse } from "./device";
import type { ListDevicesRequest } from "./device";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 设备注册与状态服务（云端中间件实现）
 *
 * @generated from protobuf service remote_control.cloud.v1.DeviceRegistryService
 */
export interface IDeviceRegistryServiceClient {
    /**
     * 仅保留清单查询（供控制端使用）
     *
     * @generated from protobuf rpc: ListDevices
     */
    listDevices(input: ListDevicesRequest, options?: RpcOptions): UnaryCall<ListDevicesRequest, ListDevicesResponse>;
    /**
     * Agent 主动连接 Cloud 的控制面双向流：连接、心跳、命令请求/响应
     *
     * @generated from protobuf rpc: ConnectAgent
     */
    connectAgent(options?: RpcOptions): DuplexStreamingCall<AgentMessage, CloudMessage>;
    /**
     * 日志上报（Agent -> Cloud）。用于大体量/连续日志，避免阻塞控制面流。
     *
     * @generated from protobuf rpc: StreamLogs
     */
    streamLogs(options?: RpcOptions): DuplexStreamingCall<LogLine, LogAck>;
}
/**
 * 设备注册与状态服务（云端中间件实现）
 *
 * @generated from protobuf service remote_control.cloud.v1.DeviceRegistryService
 */
export class DeviceRegistryServiceClient implements IDeviceRegistryServiceClient, ServiceInfo {
    typeName = DeviceRegistryService.typeName;
    methods = DeviceRegistryService.methods;
    options = DeviceRegistryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 仅保留清单查询（供控制端使用）
     *
     * @generated from protobuf rpc: ListDevices
     */
    listDevices(input: ListDevicesRequest, options?: RpcOptions): UnaryCall<ListDevicesRequest, ListDevicesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDevicesRequest, ListDevicesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Agent 主动连接 Cloud 的控制面双向流：连接、心跳、命令请求/响应
     *
     * @generated from protobuf rpc: ConnectAgent
     */
    connectAgent(options?: RpcOptions): DuplexStreamingCall<AgentMessage, CloudMessage> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AgentMessage, CloudMessage>("duplex", this._transport, method, opt);
    }
    /**
     * 日志上报（Agent -> Cloud）。用于大体量/连续日志，避免阻塞控制面流。
     *
     * @generated from protobuf rpc: StreamLogs
     */
    streamLogs(options?: RpcOptions): DuplexStreamingCall<LogLine, LogAck> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogLine, LogAck>("duplex", this._transport, method, opt);
    }
}
