// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "cloud/device.proto" (package "remote_control.cloud.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message remote_control.cloud.v1.ListDevicesRequest
 */
export interface ListDevicesRequest {
}
/**
 * @generated from protobuf message remote_control.cloud.v1.DeviceInfo
 */
export interface DeviceInfo {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string address = 3
     */
    address: string;
    /**
     * @generated from protobuf field: string status = 4
     */
    status: string; // online/offline
}
/**
 * @generated from protobuf message remote_control.cloud.v1.ListDevicesResponse
 */
export interface ListDevicesResponse {
    /**
     * @generated from protobuf field: repeated remote_control.cloud.v1.DeviceInfo devices = 1
     */
    devices: DeviceInfo[];
}
/**
 * Agent到Cloud的消息
 *
 * @generated from protobuf message remote_control.cloud.v1.AgentMessage
 */
export interface AgentMessage {
    /**
     * @generated from protobuf oneof: message
     */
    message: {
        oneofKind: "connect";
        /**
         * @generated from protobuf field: remote_control.cloud.v1.AgentConnect connect = 1
         */
        connect: AgentConnect; // Agent连接注册
    } | {
        oneofKind: "heartbeat";
        /**
         * @generated from protobuf field: remote_control.cloud.v1.AgentHeartbeat heartbeat = 2
         */
        heartbeat: AgentHeartbeat; // Agent心跳
    } | {
        oneofKind: "response";
        /**
         * @generated from protobuf field: remote_control.cloud.v1.CommandResponse response = 3
         */
        response: CommandResponse; // 命令执行结果
    } | {
        oneofKind: undefined;
    };
}
/**
 * Cloud到Agent的消息
 *
 * @generated from protobuf message remote_control.cloud.v1.CloudMessage
 */
export interface CloudMessage {
    /**
     * @generated from protobuf oneof: message
     */
    message: {
        oneofKind: "connectAck";
        /**
         * @generated from protobuf field: remote_control.cloud.v1.ConnectAck connect_ack = 1
         */
        connectAck: ConnectAck; // 连接确认
    } | {
        oneofKind: "command";
        /**
         * @generated from protobuf field: remote_control.cloud.v1.CommandRequest command = 2
         */
        command: CommandRequest; // 命令执行请求
    } | {
        oneofKind: "ping";
        /**
         * @generated from protobuf field: remote_control.cloud.v1.Ping ping = 3
         */
        ping: Ping; // 心跳ping
    } | {
        oneofKind: undefined;
    };
}
/**
 * Agent连接注册
 *
 * @generated from protobuf message remote_control.cloud.v1.AgentConnect
 */
export interface AgentConnect {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: string version = 4
     */
    version: string;
}
/**
 * 连接确认
 *
 * @generated from protobuf message remote_control.cloud.v1.ConnectAck
 */
export interface ConnectAck {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: string session_id = 3
     */
    sessionId: string;
}
/**
 * Agent心跳
 *
 * @generated from protobuf message remote_control.cloud.v1.AgentHeartbeat
 */
export interface AgentHeartbeat {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: int64 timestamp = 2
     */
    timestamp: string;
}
/**
 * 命令执行请求（Cloud->Agent）
 *
 * @generated from protobuf message remote_control.cloud.v1.CommandRequest
 */
export interface CommandRequest {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string; // 请求ID，用于响应匹配
    /**
     * @generated from protobuf field: bytes payload = 2
     */
    payload: Uint8Array; // 序列化的请求，类型由 method 指示
    /**
     * @generated from protobuf field: remote_control.cloud.v1.ControllerMethod method = 3
     */
    method: ControllerMethod; // 控制器方法类型
}
/**
 * 命令执行响应（Agent->Cloud）
 *
 * @generated from protobuf message remote_control.cloud.v1.CommandResponse
 */
export interface CommandResponse {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string; // 对应的请求ID
    /**
     * @generated from protobuf field: bytes payload = 2
     */
    payload: Uint8Array; // 序列化的ExecuteCommandSetResponse
}
/**
 * Ping消息
 *
 * @generated from protobuf message remote_control.cloud.v1.Ping
 */
export interface Ping {
    /**
     * @generated from protobuf field: int64 timestamp = 1
     */
    timestamp: string;
}
/**
 * 日志行（分片）
 *
 * @generated from protobuf message remote_control.cloud.v1.LogLine
 */
export interface LogLine {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string stream_id = 2
     */
    streamId: string; // 日志流会话ID
    /**
     * @generated from protobuf field: int64 seq = 3
     */
    seq: string; // 递增序号
    /**
     * @generated from protobuf field: int64 ts = 4
     */
    ts: string; // 发送时间戳（ns）
    /**
     * @generated from protobuf field: string level = 5
     */
    level: string; // INFO/WARN/ERROR
    /**
     * @generated from protobuf field: bytes chunk = 6
     */
    chunk: Uint8Array; // 按块切分的日志内容（UTF-8或二进制）
    /**
     * @generated from protobuf field: bool end = 7
     */
    end: boolean; // 本流结束
}
/**
 * 日志确认
 *
 * @generated from protobuf message remote_control.cloud.v1.LogAck
 */
export interface LogAck {
    /**
     * @generated from protobuf field: string stream_id = 1
     */
    streamId: string;
    /**
     * @generated from protobuf field: int64 ack_seq = 2
     */
    ackSeq: string; // 已确认的最大序号
}
/**
 * 标识要在 Agent 上调用的控制器方法
 *
 * @generated from protobuf enum remote_control.cloud.v1.ControllerMethod
 */
export enum ControllerMethod {
    /**
     * 执行命令集
     *
     * @generated from protobuf enum value: CONTROLLER_METHOD_EXECUTE = 0;
     */
    EXECUTE = 0,
    /**
     * 存储命令集
     *
     * @generated from protobuf enum value: CONTROLLER_METHOD_STORE = 1;
     */
    STORE = 1,
    /**
     * 更新命令集
     *
     * @generated from protobuf enum value: CONTROLLER_METHOD_UPDATE = 2;
     */
    UPDATE = 2,
    /**
     * 删除命令集
     *
     * @generated from protobuf enum value: CONTROLLER_METHOD_DELETE = 3;
     */
    DELETE = 3,
    /**
     * 获取全部命令集
     *
     * @generated from protobuf enum value: CONTROLLER_METHOD_LIST = 4;
     */
    LIST = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class ListDevicesRequest$Type extends MessageType<ListDevicesRequest> {
    constructor() {
        super("remote_control.cloud.v1.ListDevicesRequest", []);
    }
    create(value?: PartialMessage<ListDevicesRequest>): ListDevicesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListDevicesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListDevicesRequest): ListDevicesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListDevicesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ListDevicesRequest
 */
export const ListDevicesRequest = new ListDevicesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeviceInfo$Type extends MessageType<DeviceInfo> {
    constructor() {
        super("remote_control.cloud.v1.DeviceInfo", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeviceInfo>): DeviceInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.name = "";
        message.address = "";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<DeviceInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeviceInfo): DeviceInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string address */ 3:
                    message.address = reader.string();
                    break;
                case /* string status */ 4:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeviceInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string address = 3; */
        if (message.address !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.address);
        /* string status = 4; */
        if (message.status !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.DeviceInfo
 */
export const DeviceInfo = new DeviceInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListDevicesResponse$Type extends MessageType<ListDevicesResponse> {
    constructor() {
        super("remote_control.cloud.v1.ListDevicesResponse", [
            { no: 1, name: "devices", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DeviceInfo }
        ]);
    }
    create(value?: PartialMessage<ListDevicesResponse>): ListDevicesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.devices = [];
        if (value !== undefined)
            reflectionMergePartial<ListDevicesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListDevicesResponse): ListDevicesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated remote_control.cloud.v1.DeviceInfo devices */ 1:
                    message.devices.push(DeviceInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListDevicesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated remote_control.cloud.v1.DeviceInfo devices = 1; */
        for (let i = 0; i < message.devices.length; i++)
            DeviceInfo.internalBinaryWrite(message.devices[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ListDevicesResponse
 */
export const ListDevicesResponse = new ListDevicesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AgentMessage$Type extends MessageType<AgentMessage> {
    constructor() {
        super("remote_control.cloud.v1.AgentMessage", [
            { no: 1, name: "connect", kind: "message", oneof: "message", T: () => AgentConnect },
            { no: 2, name: "heartbeat", kind: "message", oneof: "message", T: () => AgentHeartbeat },
            { no: 3, name: "response", kind: "message", oneof: "message", T: () => CommandResponse }
        ]);
    }
    create(value?: PartialMessage<AgentMessage>): AgentMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<AgentMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AgentMessage): AgentMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* remote_control.cloud.v1.AgentConnect connect */ 1:
                    message.message = {
                        oneofKind: "connect",
                        connect: AgentConnect.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).connect)
                    };
                    break;
                case /* remote_control.cloud.v1.AgentHeartbeat heartbeat */ 2:
                    message.message = {
                        oneofKind: "heartbeat",
                        heartbeat: AgentHeartbeat.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).heartbeat)
                    };
                    break;
                case /* remote_control.cloud.v1.CommandResponse response */ 3:
                    message.message = {
                        oneofKind: "response",
                        response: CommandResponse.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).response)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgentMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* remote_control.cloud.v1.AgentConnect connect = 1; */
        if (message.message.oneofKind === "connect")
            AgentConnect.internalBinaryWrite(message.message.connect, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* remote_control.cloud.v1.AgentHeartbeat heartbeat = 2; */
        if (message.message.oneofKind === "heartbeat")
            AgentHeartbeat.internalBinaryWrite(message.message.heartbeat, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* remote_control.cloud.v1.CommandResponse response = 3; */
        if (message.message.oneofKind === "response")
            CommandResponse.internalBinaryWrite(message.message.response, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.AgentMessage
 */
export const AgentMessage = new AgentMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CloudMessage$Type extends MessageType<CloudMessage> {
    constructor() {
        super("remote_control.cloud.v1.CloudMessage", [
            { no: 1, name: "connect_ack", kind: "message", oneof: "message", T: () => ConnectAck },
            { no: 2, name: "command", kind: "message", oneof: "message", T: () => CommandRequest },
            { no: 3, name: "ping", kind: "message", oneof: "message", T: () => Ping }
        ]);
    }
    create(value?: PartialMessage<CloudMessage>): CloudMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<CloudMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CloudMessage): CloudMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* remote_control.cloud.v1.ConnectAck connect_ack */ 1:
                    message.message = {
                        oneofKind: "connectAck",
                        connectAck: ConnectAck.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).connectAck)
                    };
                    break;
                case /* remote_control.cloud.v1.CommandRequest command */ 2:
                    message.message = {
                        oneofKind: "command",
                        command: CommandRequest.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).command)
                    };
                    break;
                case /* remote_control.cloud.v1.Ping ping */ 3:
                    message.message = {
                        oneofKind: "ping",
                        ping: Ping.internalBinaryRead(reader, reader.uint32(), options, (message.message as any).ping)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CloudMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* remote_control.cloud.v1.ConnectAck connect_ack = 1; */
        if (message.message.oneofKind === "connectAck")
            ConnectAck.internalBinaryWrite(message.message.connectAck, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* remote_control.cloud.v1.CommandRequest command = 2; */
        if (message.message.oneofKind === "command")
            CommandRequest.internalBinaryWrite(message.message.command, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* remote_control.cloud.v1.Ping ping = 3; */
        if (message.message.oneofKind === "ping")
            Ping.internalBinaryWrite(message.message.ping, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.CloudMessage
 */
export const CloudMessage = new CloudMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AgentConnect$Type extends MessageType<AgentConnect> {
    constructor() {
        super("remote_control.cloud.v1.AgentConnect", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AgentConnect>): AgentConnect {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.name = "";
        message.version = "";
        if (value !== undefined)
            reflectionMergePartial<AgentConnect>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AgentConnect): AgentConnect {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string version */ 4:
                    message.version = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgentConnect, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string version = 4; */
        if (message.version !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.version);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.AgentConnect
 */
export const AgentConnect = new AgentConnect$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectAck$Type extends MessageType<ConnectAck> {
    constructor() {
        super("remote_control.cloud.v1.ConnectAck", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConnectAck>): ConnectAck {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.sessionId = "";
        if (value !== undefined)
            reflectionMergePartial<ConnectAck>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectAck): ConnectAck {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string session_id */ 3:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectAck, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string session_id = 3; */
        if (message.sessionId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ConnectAck
 */
export const ConnectAck = new ConnectAck$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AgentHeartbeat$Type extends MessageType<AgentHeartbeat> {
    constructor() {
        super("remote_control.cloud.v1.AgentHeartbeat", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<AgentHeartbeat>): AgentHeartbeat {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.timestamp = "0";
        if (value !== undefined)
            reflectionMergePartial<AgentHeartbeat>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AgentHeartbeat): AgentHeartbeat {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* int64 timestamp */ 2:
                    message.timestamp = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgentHeartbeat, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* int64 timestamp = 2; */
        if (message.timestamp !== "0")
            writer.tag(2, WireType.Varint).int64(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.AgentHeartbeat
 */
export const AgentHeartbeat = new AgentHeartbeat$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommandRequest$Type extends MessageType<CommandRequest> {
    constructor() {
        super("remote_control.cloud.v1.CommandRequest", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "method", kind: "enum", T: () => ["remote_control.cloud.v1.ControllerMethod", ControllerMethod, "CONTROLLER_METHOD_"] }
        ]);
    }
    create(value?: PartialMessage<CommandRequest>): CommandRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.payload = new Uint8Array(0);
        message.method = 0;
        if (value !== undefined)
            reflectionMergePartial<CommandRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommandRequest): CommandRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* bytes payload */ 2:
                    message.payload = reader.bytes();
                    break;
                case /* remote_control.cloud.v1.ControllerMethod method */ 3:
                    message.method = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommandRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* bytes payload = 2; */
        if (message.payload.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.payload);
        /* remote_control.cloud.v1.ControllerMethod method = 3; */
        if (message.method !== 0)
            writer.tag(3, WireType.Varint).int32(message.method);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.CommandRequest
 */
export const CommandRequest = new CommandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommandResponse$Type extends MessageType<CommandResponse> {
    constructor() {
        super("remote_control.cloud.v1.CommandResponse", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<CommandResponse>): CommandResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.payload = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<CommandResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommandResponse): CommandResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* bytes payload */ 2:
                    message.payload = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommandResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* bytes payload = 2; */
        if (message.payload.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.payload);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.CommandResponse
 */
export const CommandResponse = new CommandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Ping$Type extends MessageType<Ping> {
    constructor() {
        super("remote_control.cloud.v1.Ping", [
            { no: 1, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<Ping>): Ping {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.timestamp = "0";
        if (value !== undefined)
            reflectionMergePartial<Ping>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Ping): Ping {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 timestamp */ 1:
                    message.timestamp = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Ping, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 timestamp = 1; */
        if (message.timestamp !== "0")
            writer.tag(1, WireType.Varint).int64(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.Ping
 */
export const Ping = new Ping$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogLine$Type extends MessageType<LogLine> {
    constructor() {
        super("remote_control.cloud.v1.LogLine", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "seq", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "ts", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "level", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "chunk", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 7, name: "end", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<LogLine>): LogLine {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.streamId = "";
        message.seq = "0";
        message.ts = "0";
        message.level = "";
        message.chunk = new Uint8Array(0);
        message.end = false;
        if (value !== undefined)
            reflectionMergePartial<LogLine>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogLine): LogLine {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string stream_id */ 2:
                    message.streamId = reader.string();
                    break;
                case /* int64 seq */ 3:
                    message.seq = reader.int64().toString();
                    break;
                case /* int64 ts */ 4:
                    message.ts = reader.int64().toString();
                    break;
                case /* string level */ 5:
                    message.level = reader.string();
                    break;
                case /* bytes chunk */ 6:
                    message.chunk = reader.bytes();
                    break;
                case /* bool end */ 7:
                    message.end = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogLine, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string stream_id = 2; */
        if (message.streamId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.streamId);
        /* int64 seq = 3; */
        if (message.seq !== "0")
            writer.tag(3, WireType.Varint).int64(message.seq);
        /* int64 ts = 4; */
        if (message.ts !== "0")
            writer.tag(4, WireType.Varint).int64(message.ts);
        /* string level = 5; */
        if (message.level !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.level);
        /* bytes chunk = 6; */
        if (message.chunk.length)
            writer.tag(6, WireType.LengthDelimited).bytes(message.chunk);
        /* bool end = 7; */
        if (message.end !== false)
            writer.tag(7, WireType.Varint).bool(message.end);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.LogLine
 */
export const LogLine = new LogLine$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogAck$Type extends MessageType<LogAck> {
    constructor() {
        super("remote_control.cloud.v1.LogAck", [
            { no: 1, name: "stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ack_seq", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<LogAck>): LogAck {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.streamId = "";
        message.ackSeq = "0";
        if (value !== undefined)
            reflectionMergePartial<LogAck>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogAck): LogAck {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string stream_id */ 1:
                    message.streamId = reader.string();
                    break;
                case /* int64 ack_seq */ 2:
                    message.ackSeq = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogAck, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string stream_id = 1; */
        if (message.streamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streamId);
        /* int64 ack_seq = 2; */
        if (message.ackSeq !== "0")
            writer.tag(2, WireType.Varint).int64(message.ackSeq);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.LogAck
 */
export const LogAck = new LogAck$Type();
/**
 * @generated ServiceType for protobuf service remote_control.cloud.v1.DeviceRegistryService
 */
export const DeviceRegistryService = new ServiceType("remote_control.cloud.v1.DeviceRegistryService", [
    { name: "ListDevices", options: {}, I: ListDevicesRequest, O: ListDevicesResponse },
    { name: "ConnectAgent", serverStreaming: true, clientStreaming: true, options: {}, I: AgentMessage, O: CloudMessage },
    { name: "StreamLogs", serverStreaming: true, clientStreaming: true, options: {}, I: LogLine, O: LogAck }
]);
