// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "cloud/gateway.proto" (package "remote_control.cloud.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { GatewayService } from "./gateway";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ExecuteCommandSetResponse } from "../remote_control";
import type { ExecuteOnDeviceRequest } from "./gateway";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 云端网关服务：前端调用此服务，由云端转发到具体设备上的 Agent
 *
 * @generated from protobuf service remote_control.cloud.v1.GatewayService
 */
export interface IGatewayServiceClient {
    /**
     * @generated from protobuf rpc: ExecuteOnDevice
     */
    executeOnDevice(input: ExecuteOnDeviceRequest, options?: RpcOptions): UnaryCall<ExecuteOnDeviceRequest, ExecuteCommandSetResponse>;
}
/**
 * 云端网关服务：前端调用此服务，由云端转发到具体设备上的 Agent
 *
 * @generated from protobuf service remote_control.cloud.v1.GatewayService
 */
export class GatewayServiceClient implements IGatewayServiceClient, ServiceInfo {
    typeName = GatewayService.typeName;
    methods = GatewayService.methods;
    options = GatewayService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ExecuteOnDevice
     */
    executeOnDevice(input: ExecuteOnDeviceRequest, options?: RpcOptions): UnaryCall<ExecuteOnDeviceRequest, ExecuteCommandSetResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ExecuteOnDeviceRequest, ExecuteCommandSetResponse>("unary", this._transport, method, opt, input);
    }
}
