// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "cloud/gateway.proto" (package "remote_control.cloud.v1", syntax proto3)
// tslint:disable
import { DeleteCommandSetResponse } from "../remote_control";
import { UpdateCommandSetResponse } from "../remote_control";
import { StoreCommandSetResponse } from "../remote_control";
import { GetAllCommandSetsResponse } from "../remote_control";
import { ExecuteCommandSetResponse } from "../remote_control";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { DeleteCommandSetRequest } from "../remote_control";
import { UpdateCommandSetRequest } from "../remote_control";
import { StoreCommandSetRequest } from "../remote_control";
import { GetAllCommandSetsRequest } from "../remote_control";
import { ExecuteCommandSetRequest } from "../remote_control";
/**
 * @generated from protobuf message remote_control.cloud.v1.ExecuteOnDeviceRequest
 */
export interface ExecuteOnDeviceRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string; // 目标设备ID
    /**
     * @generated from protobuf field: remote_control.ExecuteCommandSetRequest request = 2
     */
    request?: ExecuteCommandSetRequest; // 透传到 Agent 的请求
}
/**
 * @generated from protobuf message remote_control.cloud.v1.ListDeviceCommandSetsRequest
 */
export interface ListDeviceCommandSetsRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: remote_control.GetAllCommandSetsRequest request = 2
     */
    request?: GetAllCommandSetsRequest; // 空请求
}
/**
 * @generated from protobuf message remote_control.cloud.v1.StoreOnDeviceRequest
 */
export interface StoreOnDeviceRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: remote_control.StoreCommandSetRequest request = 2
     */
    request?: StoreCommandSetRequest;
}
/**
 * @generated from protobuf message remote_control.cloud.v1.UpdateOnDeviceRequest
 */
export interface UpdateOnDeviceRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: remote_control.UpdateCommandSetRequest request = 2
     */
    request?: UpdateCommandSetRequest;
}
/**
 * @generated from protobuf message remote_control.cloud.v1.DeleteOnDeviceRequest
 */
export interface DeleteOnDeviceRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: remote_control.DeleteCommandSetRequest request = 2
     */
    request?: DeleteCommandSetRequest;
}
// @generated message type with reflection information, may provide speed optimized methods
class ExecuteOnDeviceRequest$Type extends MessageType<ExecuteOnDeviceRequest> {
    constructor() {
        super("remote_control.cloud.v1.ExecuteOnDeviceRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request", kind: "message", T: () => ExecuteCommandSetRequest }
        ]);
    }
    create(value?: PartialMessage<ExecuteOnDeviceRequest>): ExecuteOnDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<ExecuteOnDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExecuteOnDeviceRequest): ExecuteOnDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* remote_control.ExecuteCommandSetRequest request */ 2:
                    message.request = ExecuteCommandSetRequest.internalBinaryRead(reader, reader.uint32(), options, message.request);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExecuteOnDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* remote_control.ExecuteCommandSetRequest request = 2; */
        if (message.request)
            ExecuteCommandSetRequest.internalBinaryWrite(message.request, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ExecuteOnDeviceRequest
 */
export const ExecuteOnDeviceRequest = new ExecuteOnDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListDeviceCommandSetsRequest$Type extends MessageType<ListDeviceCommandSetsRequest> {
    constructor() {
        super("remote_control.cloud.v1.ListDeviceCommandSetsRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request", kind: "message", T: () => GetAllCommandSetsRequest }
        ]);
    }
    create(value?: PartialMessage<ListDeviceCommandSetsRequest>): ListDeviceCommandSetsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<ListDeviceCommandSetsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListDeviceCommandSetsRequest): ListDeviceCommandSetsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* remote_control.GetAllCommandSetsRequest request */ 2:
                    message.request = GetAllCommandSetsRequest.internalBinaryRead(reader, reader.uint32(), options, message.request);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListDeviceCommandSetsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* remote_control.GetAllCommandSetsRequest request = 2; */
        if (message.request)
            GetAllCommandSetsRequest.internalBinaryWrite(message.request, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ListDeviceCommandSetsRequest
 */
export const ListDeviceCommandSetsRequest = new ListDeviceCommandSetsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StoreOnDeviceRequest$Type extends MessageType<StoreOnDeviceRequest> {
    constructor() {
        super("remote_control.cloud.v1.StoreOnDeviceRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request", kind: "message", T: () => StoreCommandSetRequest }
        ]);
    }
    create(value?: PartialMessage<StoreOnDeviceRequest>): StoreOnDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<StoreOnDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StoreOnDeviceRequest): StoreOnDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* remote_control.StoreCommandSetRequest request */ 2:
                    message.request = StoreCommandSetRequest.internalBinaryRead(reader, reader.uint32(), options, message.request);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StoreOnDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* remote_control.StoreCommandSetRequest request = 2; */
        if (message.request)
            StoreCommandSetRequest.internalBinaryWrite(message.request, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.StoreOnDeviceRequest
 */
export const StoreOnDeviceRequest = new StoreOnDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateOnDeviceRequest$Type extends MessageType<UpdateOnDeviceRequest> {
    constructor() {
        super("remote_control.cloud.v1.UpdateOnDeviceRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request", kind: "message", T: () => UpdateCommandSetRequest }
        ]);
    }
    create(value?: PartialMessage<UpdateOnDeviceRequest>): UpdateOnDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateOnDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateOnDeviceRequest): UpdateOnDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* remote_control.UpdateCommandSetRequest request */ 2:
                    message.request = UpdateCommandSetRequest.internalBinaryRead(reader, reader.uint32(), options, message.request);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateOnDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* remote_control.UpdateCommandSetRequest request = 2; */
        if (message.request)
            UpdateCommandSetRequest.internalBinaryWrite(message.request, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.UpdateOnDeviceRequest
 */
export const UpdateOnDeviceRequest = new UpdateOnDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteOnDeviceRequest$Type extends MessageType<DeleteOnDeviceRequest> {
    constructor() {
        super("remote_control.cloud.v1.DeleteOnDeviceRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request", kind: "message", T: () => DeleteCommandSetRequest }
        ]);
    }
    create(value?: PartialMessage<DeleteOnDeviceRequest>): DeleteOnDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteOnDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteOnDeviceRequest): DeleteOnDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* remote_control.DeleteCommandSetRequest request */ 2:
                    message.request = DeleteCommandSetRequest.internalBinaryRead(reader, reader.uint32(), options, message.request);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteOnDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* remote_control.DeleteCommandSetRequest request = 2; */
        if (message.request)
            DeleteCommandSetRequest.internalBinaryWrite(message.request, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.DeleteOnDeviceRequest
 */
export const DeleteOnDeviceRequest = new DeleteOnDeviceRequest$Type();
/**
 * @generated ServiceType for protobuf service remote_control.cloud.v1.GatewayService
 */
export const GatewayService = new ServiceType("remote_control.cloud.v1.GatewayService", [
    { name: "ExecuteOnDevice", options: {}, I: ExecuteOnDeviceRequest, O: ExecuteCommandSetResponse },
    { name: "ListDeviceCommandSets", options: {}, I: ListDeviceCommandSetsRequest, O: GetAllCommandSetsResponse },
    { name: "StoreOnDevice", options: {}, I: StoreOnDeviceRequest, O: StoreCommandSetResponse },
    { name: "UpdateOnDevice", options: {}, I: UpdateOnDeviceRequest, O: UpdateCommandSetResponse },
    { name: "DeleteOnDevice", options: {}, I: DeleteOnDeviceRequest, O: DeleteCommandSetResponse }
]);
