// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "cloud/gateway.proto" (package "remote_control.cloud.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message remote_control.cloud.v1.ProxyUnaryRequest
 */
export interface ProxyUnaryRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string; // 目标设备/网关ID
    /**
     * @generated from protobuf field: string method = 2
     */
    method: string; // 目标方法名，例如 "/remote_control.home.HomeService/ListDevices"
    /**
     * @generated from protobuf field: bytes payload = 3
     */
    payload: Uint8Array; // 请求 payload（protobuf wire bytes）
}
/**
 * @generated from protobuf message remote_control.cloud.v1.ProxyUnaryResponse
 */
export interface ProxyUnaryResponse {
    /**
     * @generated from protobuf field: bytes payload = 1
     */
    payload: Uint8Array; // 响应 payload（protobuf wire bytes）
}
/**
 * @generated from protobuf message remote_control.cloud.v1.ProxyStreamRequest
 */
export interface ProxyStreamRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string; // 目标设备/网关ID
    /**
     * @generated from protobuf field: string method = 2
     */
    method: string; // 目标方法名，例如 "/remote_control.home.HomeService/WatchDevices"
    /**
     * @generated from protobuf field: bytes payload = 3
     */
    payload: Uint8Array; // 请求 payload（protobuf wire bytes）
}
/**
 * @generated from protobuf message remote_control.cloud.v1.ProxyStreamResponse
 */
export interface ProxyStreamResponse {
    /**
     * @generated from protobuf field: bytes payload = 1
     */
    payload: Uint8Array; // 流式响应 payload（protobuf wire bytes）
}
// @generated message type with reflection information, may provide speed optimized methods
class ProxyUnaryRequest$Type extends MessageType<ProxyUnaryRequest> {
    constructor() {
        super("remote_control.cloud.v1.ProxyUnaryRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<ProxyUnaryRequest>): ProxyUnaryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.method = "";
        message.payload = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<ProxyUnaryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProxyUnaryRequest): ProxyUnaryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string method */ 2:
                    message.method = reader.string();
                    break;
                case /* bytes payload */ 3:
                    message.payload = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProxyUnaryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string method = 2; */
        if (message.method !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.method);
        /* bytes payload = 3; */
        if (message.payload.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.payload);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ProxyUnaryRequest
 */
export const ProxyUnaryRequest = new ProxyUnaryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProxyUnaryResponse$Type extends MessageType<ProxyUnaryResponse> {
    constructor() {
        super("remote_control.cloud.v1.ProxyUnaryResponse", [
            { no: 1, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<ProxyUnaryResponse>): ProxyUnaryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.payload = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<ProxyUnaryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProxyUnaryResponse): ProxyUnaryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes payload */ 1:
                    message.payload = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProxyUnaryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes payload = 1; */
        if (message.payload.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.payload);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ProxyUnaryResponse
 */
export const ProxyUnaryResponse = new ProxyUnaryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProxyStreamRequest$Type extends MessageType<ProxyStreamRequest> {
    constructor() {
        super("remote_control.cloud.v1.ProxyStreamRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<ProxyStreamRequest>): ProxyStreamRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.method = "";
        message.payload = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<ProxyStreamRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProxyStreamRequest): ProxyStreamRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string method */ 2:
                    message.method = reader.string();
                    break;
                case /* bytes payload */ 3:
                    message.payload = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProxyStreamRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string method = 2; */
        if (message.method !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.method);
        /* bytes payload = 3; */
        if (message.payload.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.payload);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ProxyStreamRequest
 */
export const ProxyStreamRequest = new ProxyStreamRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProxyStreamResponse$Type extends MessageType<ProxyStreamResponse> {
    constructor() {
        super("remote_control.cloud.v1.ProxyStreamResponse", [
            { no: 1, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<ProxyStreamResponse>): ProxyStreamResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.payload = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<ProxyStreamResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProxyStreamResponse): ProxyStreamResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes payload */ 1:
                    message.payload = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProxyStreamResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes payload = 1; */
        if (message.payload.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.payload);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.cloud.v1.ProxyStreamResponse
 */
export const ProxyStreamResponse = new ProxyStreamResponse$Type();
/**
 * @generated ServiceType for protobuf service remote_control.cloud.v1.GatewayService
 */
export const GatewayService = new ServiceType("remote_control.cloud.v1.GatewayService", [
    { name: "Unary", options: {}, I: ProxyUnaryRequest, O: ProxyUnaryResponse },
    { name: "Stream", serverStreaming: true, options: {}, I: ProxyStreamRequest, O: ProxyStreamResponse }
]);
