// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "cloud/gateway.proto" (package "remote_control.cloud.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { GatewayService } from "./gateway";
import type { TriggerAutomationResponse } from "../home/service";
import type { TriggerAutomationRequest } from "./gateway";
import type { SetAutomationEnabledResponse } from "../home/service";
import type { SetAutomationEnabledRequest } from "./gateway";
import type { DeleteAutomationResponse } from "../home/service";
import type { DeleteAutomationRequest } from "./gateway";
import type { UpsertAutomationResponse } from "../home/service";
import type { UpsertAutomationRequest } from "./gateway";
import type { ListAutomationsResponse } from "../home/service";
import type { ListAutomationsRequest } from "./gateway";
import type { InvokeActionResponse } from "../home/service";
import type { InvokeActionRequest } from "./gateway";
import type { DeleteDeviceResponse } from "../home/service";
import type { DeleteDeviceRequest } from "./gateway";
import type { UpsertDeviceResponse } from "../home/service";
import type { UpsertDeviceRequest } from "./gateway";
import type { DeviceEvent } from "../home/service";
import type { WatchDevicesRequest } from "./gateway";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListDevicesResponse } from "../home/service";
import type { ListDevicesRequest } from "./gateway";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 云端网关服务：前端调用此服务，由云端转发到具体设备上的 HomeService
 *
 * @generated from protobuf service remote_control.cloud.v1.GatewayService
 */
export interface IGatewayServiceClient {
    /**
     * 列出设备（转发到 HomeService）
     *
     * @generated from protobuf rpc: ListDevices
     */
    listDevices(input: ListDevicesRequest, options?: RpcOptions): UnaryCall<ListDevicesRequest, ListDevicesResponse>;
    /**
     * 监听设备事件（转发到 HomeService）
     *
     * @generated from protobuf rpc: WatchDevices
     */
    watchDevices(input: WatchDevicesRequest, options?: RpcOptions): ServerStreamingCall<WatchDevicesRequest, DeviceEvent>;
    /**
     * 注册/更新设备（转发到 HomeService）
     *
     * @generated from protobuf rpc: UpsertDevice
     */
    upsertDevice(input: UpsertDeviceRequest, options?: RpcOptions): UnaryCall<UpsertDeviceRequest, UpsertDeviceResponse>;
    /**
     * 删除设备（转发到 HomeService）
     *
     * @generated from protobuf rpc: DeleteDevice
     */
    deleteDevice(input: DeleteDeviceRequest, options?: RpcOptions): UnaryCall<DeleteDeviceRequest, DeleteDeviceResponse>;
    /**
     * 调用设备动作（转发到 HomeService）
     *
     * @generated from protobuf rpc: InvokeAction
     */
    invokeAction(input: InvokeActionRequest, options?: RpcOptions): UnaryCall<InvokeActionRequest, InvokeActionResponse>;
    /**
     * 自动化：查询/管理/触发（转发到 AutomationService）
     *
     * @generated from protobuf rpc: ListAutomations
     */
    listAutomations(input: ListAutomationsRequest, options?: RpcOptions): UnaryCall<ListAutomationsRequest, ListAutomationsResponse>;
    /**
     * @generated from protobuf rpc: UpsertAutomation
     */
    upsertAutomation(input: UpsertAutomationRequest, options?: RpcOptions): UnaryCall<UpsertAutomationRequest, UpsertAutomationResponse>;
    /**
     * @generated from protobuf rpc: DeleteAutomation
     */
    deleteAutomation(input: DeleteAutomationRequest, options?: RpcOptions): UnaryCall<DeleteAutomationRequest, DeleteAutomationResponse>;
    /**
     * @generated from protobuf rpc: SetAutomationEnabled
     */
    setAutomationEnabled(input: SetAutomationEnabledRequest, options?: RpcOptions): UnaryCall<SetAutomationEnabledRequest, SetAutomationEnabledResponse>;
    /**
     * @generated from protobuf rpc: TriggerAutomation
     */
    triggerAutomation(input: TriggerAutomationRequest, options?: RpcOptions): UnaryCall<TriggerAutomationRequest, TriggerAutomationResponse>;
}
/**
 * 云端网关服务：前端调用此服务，由云端转发到具体设备上的 HomeService
 *
 * @generated from protobuf service remote_control.cloud.v1.GatewayService
 */
export class GatewayServiceClient implements IGatewayServiceClient, ServiceInfo {
    typeName = GatewayService.typeName;
    methods = GatewayService.methods;
    options = GatewayService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 列出设备（转发到 HomeService）
     *
     * @generated from protobuf rpc: ListDevices
     */
    listDevices(input: ListDevicesRequest, options?: RpcOptions): UnaryCall<ListDevicesRequest, ListDevicesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDevicesRequest, ListDevicesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 监听设备事件（转发到 HomeService）
     *
     * @generated from protobuf rpc: WatchDevices
     */
    watchDevices(input: WatchDevicesRequest, options?: RpcOptions): ServerStreamingCall<WatchDevicesRequest, DeviceEvent> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchDevicesRequest, DeviceEvent>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * 注册/更新设备（转发到 HomeService）
     *
     * @generated from protobuf rpc: UpsertDevice
     */
    upsertDevice(input: UpsertDeviceRequest, options?: RpcOptions): UnaryCall<UpsertDeviceRequest, UpsertDeviceResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpsertDeviceRequest, UpsertDeviceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 删除设备（转发到 HomeService）
     *
     * @generated from protobuf rpc: DeleteDevice
     */
    deleteDevice(input: DeleteDeviceRequest, options?: RpcOptions): UnaryCall<DeleteDeviceRequest, DeleteDeviceResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteDeviceRequest, DeleteDeviceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 调用设备动作（转发到 HomeService）
     *
     * @generated from protobuf rpc: InvokeAction
     */
    invokeAction(input: InvokeActionRequest, options?: RpcOptions): UnaryCall<InvokeActionRequest, InvokeActionResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<InvokeActionRequest, InvokeActionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 自动化：查询/管理/触发（转发到 AutomationService）
     *
     * @generated from protobuf rpc: ListAutomations
     */
    listAutomations(input: ListAutomationsRequest, options?: RpcOptions): UnaryCall<ListAutomationsRequest, ListAutomationsResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAutomationsRequest, ListAutomationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpsertAutomation
     */
    upsertAutomation(input: UpsertAutomationRequest, options?: RpcOptions): UnaryCall<UpsertAutomationRequest, UpsertAutomationResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpsertAutomationRequest, UpsertAutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAutomation
     */
    deleteAutomation(input: DeleteAutomationRequest, options?: RpcOptions): UnaryCall<DeleteAutomationRequest, DeleteAutomationResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteAutomationRequest, DeleteAutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetAutomationEnabled
     */
    setAutomationEnabled(input: SetAutomationEnabledRequest, options?: RpcOptions): UnaryCall<SetAutomationEnabledRequest, SetAutomationEnabledResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetAutomationEnabledRequest, SetAutomationEnabledResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TriggerAutomation
     */
    triggerAutomation(input: TriggerAutomationRequest, options?: RpcOptions): UnaryCall<TriggerAutomationRequest, TriggerAutomationResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<TriggerAutomationRequest, TriggerAutomationResponse>("unary", this._transport, method, opt, input);
    }
}
