// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: home/service.proto

package homepb

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdapterKind int32

const (
	AdapterKind_ADAPTER_KIND_UNSPECIFIED AdapterKind = 0
	AdapterKind_MQTT                     AdapterKind = 1
	AdapterKind_SERIAL                   AdapterKind = 2
	AdapterKind_HTTP                     AdapterKind = 3
)

// Enum value maps for AdapterKind.
var (
	AdapterKind_name = map[int32]string{
		0: "ADAPTER_KIND_UNSPECIFIED",
		1: "MQTT",
		2: "SERIAL",
		3: "HTTP",
	}
	AdapterKind_value = map[string]int32{
		"ADAPTER_KIND_UNSPECIFIED": 0,
		"MQTT":                     1,
		"SERIAL":                   2,
		"HTTP":                     3,
	}
)

func (x AdapterKind) Enum() *AdapterKind {
	p := new(AdapterKind)
	*p = x
	return p
}

func (x AdapterKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdapterKind) Descriptor() protoreflect.EnumDescriptor {
	return file_home_service_proto_enumTypes[0].Descriptor()
}

func (AdapterKind) Type() protoreflect.EnumType {
	return &file_home_service_proto_enumTypes[0]
}

func (x AdapterKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdapterKind.Descriptor instead.
func (AdapterKind) EnumDescriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{0}
}

type TelemetryEventKind int32

const (
	TelemetryEventKind_EVENT_KIND_UNSPECIFIED TelemetryEventKind = 0
	TelemetryEventKind_STATE                  TelemetryEventKind = 1 // device state update
	TelemetryEventKind_ONLINE                 TelemetryEventKind = 2 // online/offline status
	TelemetryEventKind_ACTION_RESULT          TelemetryEventKind = 3 // action execution result
	TelemetryEventKind_EVENT                  TelemetryEventKind = 4 // custom event
)

// Enum value maps for TelemetryEventKind.
var (
	TelemetryEventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "STATE",
		2: "ONLINE",
		3: "ACTION_RESULT",
		4: "EVENT",
	}
	TelemetryEventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"STATE":                  1,
		"ONLINE":                 2,
		"ACTION_RESULT":          3,
		"EVENT":                  4,
	}
)

func (x TelemetryEventKind) Enum() *TelemetryEventKind {
	p := new(TelemetryEventKind)
	*p = x
	return p
}

func (x TelemetryEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_home_service_proto_enumTypes[1].Descriptor()
}

func (TelemetryEventKind) Type() protoreflect.EnumType {
	return &file_home_service_proto_enumTypes[1]
}

func (x TelemetryEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryEventKind.Descriptor instead.
func (TelemetryEventKind) EnumDescriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{1}
}

type Adapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AdapterKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=remote_control.home.AdapterKind" json:"kind,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Adapter) Reset() {
	*x = Adapter{}
	mi := &file_home_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adapter) ProtoMessage() {}

func (x *Adapter) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adapter.ProtoReflect.Descriptor instead.
func (*Adapter) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{0}
}

func (x *Adapter) GetKind() AdapterKind {
	if x != nil {
		return x.Kind
	}
	return AdapterKind_ADAPTER_KIND_UNSPECIFIED
}

func (x *Adapter) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ActionSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgsSchema    map[string]string      `protobuf:"bytes,2,rep,name=args_schema,json=argsSchema,proto3" json:"args_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSpec) Reset() {
	*x = ActionSpec{}
	mi := &file_home_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSpec) ProtoMessage() {}

func (x *ActionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSpec.ProtoReflect.Descriptor instead.
func (*ActionSpec) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{1}
}

func (x *ActionSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionSpec) GetArgsSchema() map[string]string {
	if x != nil {
		return x.ArgsSchema
	}
	return nil
}

func (x *ActionSpec) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Room          string                 `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Online        bool                   `protobuf:"varint,6,opt,name=online,proto3" json:"online,omitempty"`
	LastSeen      int64                  `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Topics        map[string]string      `protobuf:"bytes,8,rep,name=topics,proto3" json:"topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Adapter       *Adapter               `protobuf:"bytes,9,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Actions       []*ActionSpec          `protobuf:"bytes,10,rep,name=actions,proto3" json:"actions,omitempty"`
	State         *_struct.Struct        `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_home_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Device) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Device) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Device) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Device) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Device) GetTopics() map[string]string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Device) GetAdapter() *Adapter {
	if x != nil {
		return x.Adapter
	}
	return nil
}

func (x *Device) GetActions() []*ActionSpec {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Device) GetState() *_struct.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	IncludeState  bool                   `protobuf:"varint,5,opt,name=include_state,json=includeState,proto3" json:"include_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_home_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListDevicesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListDevicesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListDevicesRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ListDevicesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListDevicesRequest) GetIncludeState() bool {
	if x != nil {
		return x.IncludeState
	}
	return false
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_home_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type WatchDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // empty for all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDevicesRequest) Reset() {
	*x = WatchDevicesRequest{}
	mi := &file_home_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDevicesRequest) ProtoMessage() {}

func (x *WatchDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDevicesRequest.ProtoReflect.Descriptor instead.
func (*WatchDevicesRequest) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{5}
}

func (x *WatchDevicesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeviceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Kind          TelemetryEventKind     `protobuf:"varint,3,opt,name=kind,proto3,enum=remote_control.home.TelemetryEventKind" json:"kind,omitempty"`
	Payload       *_struct.Struct        `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEvent) Reset() {
	*x = DeviceEvent{}
	mi := &file_home_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEvent) ProtoMessage() {}

func (x *DeviceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEvent.ProtoReflect.Descriptor instead.
func (*DeviceEvent) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *DeviceEvent) GetKind() TelemetryEventKind {
	if x != nil {
		return x.Kind
	}
	return TelemetryEventKind_EVENT_KIND_UNSPECIFIED
}

func (x *DeviceEvent) GetPayload() *_struct.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UpsertDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeviceRequest) Reset() {
	*x = UpsertDeviceRequest{}
	mi := &file_home_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceRequest) ProtoMessage() {}

func (x *UpsertDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpsertDeviceRequest) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertDeviceRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type UpsertDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeviceResponse) Reset() {
	*x = UpsertDeviceResponse{}
	mi := &file_home_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceResponse) ProtoMessage() {}

func (x *UpsertDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpsertDeviceResponse) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertDeviceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpsertDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceRequest) Reset() {
	*x = DeleteDeviceRequest{}
	mi := &file_home_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceRequest) ProtoMessage() {}

func (x *DeleteDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeleteDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceResponse) Reset() {
	*x = DeleteDeviceResponse{}
	mi := &file_home_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceResponse) ProtoMessage() {}

func (x *DeleteDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDeviceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InvokeActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Args          *_struct.Struct        `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeActionRequest) Reset() {
	*x = InvokeActionRequest{}
	mi := &file_home_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeActionRequest) ProtoMessage() {}

func (x *InvokeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeActionRequest.ProtoReflect.Descriptor instead.
func (*InvokeActionRequest) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{11}
}

func (x *InvokeActionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *InvokeActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InvokeActionRequest) GetArgs() *_struct.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *InvokeActionRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type InvokeActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CorrId        string                 `protobuf:"bytes,3,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`
	Data          *_struct.Struct        `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeActionResponse) Reset() {
	*x = InvokeActionResponse{}
	mi := &file_home_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeActionResponse) ProtoMessage() {}

func (x *InvokeActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeActionResponse.ProtoReflect.Descriptor instead.
func (*InvokeActionResponse) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{12}
}

func (x *InvokeActionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InvokeActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeActionResponse) GetCorrId() string {
	if x != nil {
		return x.CorrId
	}
	return ""
}

func (x *InvokeActionResponse) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Actor         string                 `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	Data          *_struct.Struct        `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_home_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{13}
}

func (x *LogEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogEntry) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *LogEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LogEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *LogEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *LogEntry) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // last seen id for keyset pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsRequest) Reset() {
	*x = ListLogsRequest{}
	mi := &file_home_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsRequest) ProtoMessage() {}

func (x *ListLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsRequest.ProtoReflect.Descriptor instead.
func (*ListLogsRequest) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListLogsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListLogsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ListLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLogsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsResponse) Reset() {
	*x = ListLogsResponse{}
	mi := &file_home_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsResponse) ProtoMessage() {}

func (x *ListLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsResponse.ProtoReflect.Descriptor instead.
func (*ListLogsResponse) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListLogsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CleanupLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeforeTs      int64                  `protobuf:"varint,1,opt,name=before_ts,json=beforeTs,proto3" json:"before_ts,omitempty"` // delete logs with ts < before_ts; 0 => all
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                       // optional safety cap; 0 => no cap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupLogsRequest) Reset() {
	*x = CleanupLogsRequest{}
	mi := &file_home_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupLogsRequest) ProtoMessage() {}

func (x *CleanupLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupLogsRequest.ProtoReflect.Descriptor instead.
func (*CleanupLogsRequest) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{16}
}

func (x *CleanupLogsRequest) GetBeforeTs() int64 {
	if x != nil {
		return x.BeforeTs
	}
	return 0
}

func (x *CleanupLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CleanupLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int32                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupLogsResponse) Reset() {
	*x = CleanupLogsResponse{}
	mi := &file_home_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupLogsResponse) ProtoMessage() {}

func (x *CleanupLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupLogsResponse.ProtoReflect.Descriptor instead.
func (*CleanupLogsResponse) Descriptor() ([]byte, []int) {
	return file_home_service_proto_rawDescGZIP(), []int{17}
}

func (x *CleanupLogsResponse) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_home_service_proto protoreflect.FileDescriptor

const file_home_service_proto_rawDesc = "" +
	"\n" +
	"\x12home/service.proto\x12\x13remote_control.home\x1a\x1cgoogle/protobuf/struct.proto\"\xbc\x01\n" +
	"\aAdapter\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .remote_control.home.AdapterKindR\x04kind\x12@\n" +
	"\x06config\x18\x02 \x03(\v2(.remote_control.home.Adapter.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\n" +
	"ActionSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12P\n" +
	"\vargs_schema\x18\x02 \x03(\v2/.remote_control.home.ActionSpec.ArgsSchemaEntryR\n" +
	"argsSchema\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x1a=\n" +
	"\x0fArgsSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x03\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04room\x18\x04 \x01(\tR\x04room\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06online\x18\x06 \x01(\bR\x06online\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\x12?\n" +
	"\x06topics\x18\b \x03(\v2'.remote_control.home.Device.TopicsEntryR\x06topics\x126\n" +
	"\aadapter\x18\t \x01(\v2\x1c.remote_control.home.AdapterR\aadapter\x129\n" +
	"\aactions\x18\n" +
	" \x03(\v2\x1f.remote_control.home.ActionSpecR\aactions\x12-\n" +
	"\x05state\x18\v \x01(\v2\x17.google.protobuf.StructR\x05state\x1a9\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x12ListDevicesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12#\n" +
	"\rinclude_state\x18\x05 \x01(\bR\fincludeState\"L\n" +
	"\x13ListDevicesResponse\x125\n" +
	"\adevices\x18\x01 \x03(\v2\x1b.remote_control.home.DeviceR\adevices\"'\n" +
	"\x13WatchDevicesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xaa\x01\n" +
	"\vDeviceEvent\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12;\n" +
	"\x04kind\x18\x03 \x01(\x0e2'.remote_control.home.TelemetryEventKindR\x04kind\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\"J\n" +
	"\x13UpsertDeviceRequest\x123\n" +
	"\x06device\x18\x01 \x01(\v2\x1b.remote_control.home.DeviceR\x06device\"@\n" +
	"\x14UpsertDeviceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x13DeleteDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"@\n" +
	"\x14DeleteDeviceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x01\n" +
	"\x13InvokeActionRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"\x86\x01\n" +
	"\x14InvokeActionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\acorr_id\x18\x03 \x01(\tR\x06corrId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x9b\x01\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x14\n" +
	"\x05actor\x18\x05 \x01(\tR\x05actor\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\"{\n" +
	"\x0fListLogsRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"s\n" +
	"\x10ListLogsResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.remote_control.home.LogEntryR\aentries\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"G\n" +
	"\x12CleanupLogsRequest\x12\x1b\n" +
	"\tbefore_ts\x18\x01 \x01(\x03R\bbeforeTs\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"/\n" +
	"\x13CleanupLogsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x05R\adeleted*K\n" +
	"\vAdapterKind\x12\x1c\n" +
	"\x18ADAPTER_KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04MQTT\x10\x01\x12\n" +
	"\n" +
	"\x06SERIAL\x10\x02\x12\b\n" +
	"\x04HTTP\x10\x03*e\n" +
	"\x12TelemetryEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05STATE\x10\x01\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x02\x12\x11\n" +
	"\rACTION_RESULT\x10\x03\x12\t\n" +
	"\x05EVENT\x10\x042\xfc\x03\n" +
	"\vHomeService\x12`\n" +
	"\vListDevices\x12'.remote_control.home.ListDevicesRequest\x1a(.remote_control.home.ListDevicesResponse\x12\\\n" +
	"\fWatchDevices\x12(.remote_control.home.WatchDevicesRequest\x1a .remote_control.home.DeviceEvent0\x01\x12c\n" +
	"\fUpsertDevice\x12(.remote_control.home.UpsertDeviceRequest\x1a).remote_control.home.UpsertDeviceResponse\x12c\n" +
	"\fDeleteDevice\x12(.remote_control.home.DeleteDeviceRequest\x1a).remote_control.home.DeleteDeviceResponse\x12c\n" +
	"\fInvokeAction\x12(.remote_control.home.InvokeActionRequest\x1a).remote_control.home.InvokeActionResponse2\xc9\x01\n" +
	"\fAuditService\x12W\n" +
	"\bListLogs\x12$.remote_control.home.ListLogsRequest\x1a%.remote_control.home.ListLogsResponse\x12`\n" +
	"\vCleanupLogs\x12'.remote_control.home.CleanupLogsRequest\x1a(.remote_control.home.CleanupLogsResponseB*Z(pc-remote-ctrl/backend/proto/home;homepbb\x06proto3"

var (
	file_home_service_proto_rawDescOnce sync.Once
	file_home_service_proto_rawDescData []byte
)

func file_home_service_proto_rawDescGZIP() []byte {
	file_home_service_proto_rawDescOnce.Do(func() {
		file_home_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_home_service_proto_rawDesc), len(file_home_service_proto_rawDesc)))
	})
	return file_home_service_proto_rawDescData
}

var file_home_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_home_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_home_service_proto_goTypes = []any{
	(AdapterKind)(0),             // 0: remote_control.home.AdapterKind
	(TelemetryEventKind)(0),      // 1: remote_control.home.TelemetryEventKind
	(*Adapter)(nil),              // 2: remote_control.home.Adapter
	(*ActionSpec)(nil),           // 3: remote_control.home.ActionSpec
	(*Device)(nil),               // 4: remote_control.home.Device
	(*ListDevicesRequest)(nil),   // 5: remote_control.home.ListDevicesRequest
	(*ListDevicesResponse)(nil),  // 6: remote_control.home.ListDevicesResponse
	(*WatchDevicesRequest)(nil),  // 7: remote_control.home.WatchDevicesRequest
	(*DeviceEvent)(nil),          // 8: remote_control.home.DeviceEvent
	(*UpsertDeviceRequest)(nil),  // 9: remote_control.home.UpsertDeviceRequest
	(*UpsertDeviceResponse)(nil), // 10: remote_control.home.UpsertDeviceResponse
	(*DeleteDeviceRequest)(nil),  // 11: remote_control.home.DeleteDeviceRequest
	(*DeleteDeviceResponse)(nil), // 12: remote_control.home.DeleteDeviceResponse
	(*InvokeActionRequest)(nil),  // 13: remote_control.home.InvokeActionRequest
	(*InvokeActionResponse)(nil), // 14: remote_control.home.InvokeActionResponse
	(*LogEntry)(nil),             // 15: remote_control.home.LogEntry
	(*ListLogsRequest)(nil),      // 16: remote_control.home.ListLogsRequest
	(*ListLogsResponse)(nil),     // 17: remote_control.home.ListLogsResponse
	(*CleanupLogsRequest)(nil),   // 18: remote_control.home.CleanupLogsRequest
	(*CleanupLogsResponse)(nil),  // 19: remote_control.home.CleanupLogsResponse
	nil,                          // 20: remote_control.home.Adapter.ConfigEntry
	nil,                          // 21: remote_control.home.ActionSpec.ArgsSchemaEntry
	nil,                          // 22: remote_control.home.Device.TopicsEntry
	(*_struct.Struct)(nil),       // 23: google.protobuf.Struct
}
var file_home_service_proto_depIdxs = []int32{
	0,  // 0: remote_control.home.Adapter.kind:type_name -> remote_control.home.AdapterKind
	20, // 1: remote_control.home.Adapter.config:type_name -> remote_control.home.Adapter.ConfigEntry
	21, // 2: remote_control.home.ActionSpec.args_schema:type_name -> remote_control.home.ActionSpec.ArgsSchemaEntry
	22, // 3: remote_control.home.Device.topics:type_name -> remote_control.home.Device.TopicsEntry
	2,  // 4: remote_control.home.Device.adapter:type_name -> remote_control.home.Adapter
	3,  // 5: remote_control.home.Device.actions:type_name -> remote_control.home.ActionSpec
	23, // 6: remote_control.home.Device.state:type_name -> google.protobuf.Struct
	4,  // 7: remote_control.home.ListDevicesResponse.devices:type_name -> remote_control.home.Device
	1,  // 8: remote_control.home.DeviceEvent.kind:type_name -> remote_control.home.TelemetryEventKind
	23, // 9: remote_control.home.DeviceEvent.payload:type_name -> google.protobuf.Struct
	4,  // 10: remote_control.home.UpsertDeviceRequest.device:type_name -> remote_control.home.Device
	23, // 11: remote_control.home.InvokeActionRequest.args:type_name -> google.protobuf.Struct
	23, // 12: remote_control.home.InvokeActionResponse.data:type_name -> google.protobuf.Struct
	23, // 13: remote_control.home.LogEntry.data:type_name -> google.protobuf.Struct
	15, // 14: remote_control.home.ListLogsResponse.entries:type_name -> remote_control.home.LogEntry
	5,  // 15: remote_control.home.HomeService.ListDevices:input_type -> remote_control.home.ListDevicesRequest
	7,  // 16: remote_control.home.HomeService.WatchDevices:input_type -> remote_control.home.WatchDevicesRequest
	9,  // 17: remote_control.home.HomeService.UpsertDevice:input_type -> remote_control.home.UpsertDeviceRequest
	11, // 18: remote_control.home.HomeService.DeleteDevice:input_type -> remote_control.home.DeleteDeviceRequest
	13, // 19: remote_control.home.HomeService.InvokeAction:input_type -> remote_control.home.InvokeActionRequest
	16, // 20: remote_control.home.AuditService.ListLogs:input_type -> remote_control.home.ListLogsRequest
	18, // 21: remote_control.home.AuditService.CleanupLogs:input_type -> remote_control.home.CleanupLogsRequest
	6,  // 22: remote_control.home.HomeService.ListDevices:output_type -> remote_control.home.ListDevicesResponse
	8,  // 23: remote_control.home.HomeService.WatchDevices:output_type -> remote_control.home.DeviceEvent
	10, // 24: remote_control.home.HomeService.UpsertDevice:output_type -> remote_control.home.UpsertDeviceResponse
	12, // 25: remote_control.home.HomeService.DeleteDevice:output_type -> remote_control.home.DeleteDeviceResponse
	14, // 26: remote_control.home.HomeService.InvokeAction:output_type -> remote_control.home.InvokeActionResponse
	17, // 27: remote_control.home.AuditService.ListLogs:output_type -> remote_control.home.ListLogsResponse
	19, // 28: remote_control.home.AuditService.CleanupLogs:output_type -> remote_control.home.CleanupLogsResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_home_service_proto_init() }
func file_home_service_proto_init() {
	if File_home_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_home_service_proto_rawDesc), len(file_home_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_home_service_proto_goTypes,
		DependencyIndexes: file_home_service_proto_depIdxs,
		EnumInfos:         file_home_service_proto_enumTypes,
		MessageInfos:      file_home_service_proto_msgTypes,
	}.Build()
	File_home_service_proto = out.File
	file_home_service_proto_goTypes = nil
	file_home_service_proto_depIdxs = nil
}
