// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: home/service.proto

package homepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HomeService_ListDevices_FullMethodName   = "/remote_control.home.HomeService/ListDevices"
	HomeService_WatchDevices_FullMethodName  = "/remote_control.home.HomeService/WatchDevices"
	HomeService_UpsertDevice_FullMethodName  = "/remote_control.home.HomeService/UpsertDevice"
	HomeService_ReserveDevice_FullMethodName = "/remote_control.home.HomeService/ReserveDevice"
	HomeService_DeleteDevice_FullMethodName  = "/remote_control.home.HomeService/DeleteDevice"
	HomeService_InvokeAction_FullMethodName  = "/remote_control.home.HomeService/InvokeAction"
)

// HomeServiceClient is the client API for HomeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HomeServiceClient interface {
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	WatchDevices(ctx context.Context, in *WatchDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceEvent], error)
	UpsertDevice(ctx context.Context, in *UpsertDeviceRequest, opts ...grpc.CallOption) (*UpsertDeviceResponse, error)
	ReserveDevice(ctx context.Context, in *ReserveDeviceRequest, opts ...grpc.CallOption) (*ReserveDeviceResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
	InvokeAction(ctx context.Context, in *InvokeActionRequest, opts ...grpc.CallOption) (*InvokeActionResponse, error)
}

type homeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHomeServiceClient(cc grpc.ClientConnInterface) HomeServiceClient {
	return &homeServiceClient{cc}
}

func (c *homeServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, HomeService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServiceClient) WatchDevices(ctx context.Context, in *WatchDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HomeService_ServiceDesc.Streams[0], HomeService_WatchDevices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchDevicesRequest, DeviceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomeService_WatchDevicesClient = grpc.ServerStreamingClient[DeviceEvent]

func (c *homeServiceClient) UpsertDevice(ctx context.Context, in *UpsertDeviceRequest, opts ...grpc.CallOption) (*UpsertDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertDeviceResponse)
	err := c.cc.Invoke(ctx, HomeService_UpsertDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServiceClient) ReserveDevice(ctx context.Context, in *ReserveDeviceRequest, opts ...grpc.CallOption) (*ReserveDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveDeviceResponse)
	err := c.cc.Invoke(ctx, HomeService_ReserveDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, HomeService_DeleteDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeServiceClient) InvokeAction(ctx context.Context, in *InvokeActionRequest, opts ...grpc.CallOption) (*InvokeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeActionResponse)
	err := c.cc.Invoke(ctx, HomeService_InvokeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeServiceServer is the server API for HomeService service.
// All implementations must embed UnimplementedHomeServiceServer
// for forward compatibility.
type HomeServiceServer interface {
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	WatchDevices(*WatchDevicesRequest, grpc.ServerStreamingServer[DeviceEvent]) error
	UpsertDevice(context.Context, *UpsertDeviceRequest) (*UpsertDeviceResponse, error)
	ReserveDevice(context.Context, *ReserveDeviceRequest) (*ReserveDeviceResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	InvokeAction(context.Context, *InvokeActionRequest) (*InvokeActionResponse, error)
	mustEmbedUnimplementedHomeServiceServer()
}

// UnimplementedHomeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHomeServiceServer struct{}

func (UnimplementedHomeServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedHomeServiceServer) WatchDevices(*WatchDevicesRequest, grpc.ServerStreamingServer[DeviceEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchDevices not implemented")
}
func (UnimplementedHomeServiceServer) UpsertDevice(context.Context, *UpsertDeviceRequest) (*UpsertDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertDevice not implemented")
}
func (UnimplementedHomeServiceServer) ReserveDevice(context.Context, *ReserveDeviceRequest) (*ReserveDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveDevice not implemented")
}
func (UnimplementedHomeServiceServer) DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedHomeServiceServer) InvokeAction(context.Context, *InvokeActionRequest) (*InvokeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeAction not implemented")
}
func (UnimplementedHomeServiceServer) mustEmbedUnimplementedHomeServiceServer() {}
func (UnimplementedHomeServiceServer) testEmbeddedByValue()                     {}

// UnsafeHomeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomeServiceServer will
// result in compilation errors.
type UnsafeHomeServiceServer interface {
	mustEmbedUnimplementedHomeServiceServer()
}

func RegisterHomeServiceServer(s grpc.ServiceRegistrar, srv HomeServiceServer) {
	// If the following call pancis, it indicates UnimplementedHomeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HomeService_ServiceDesc, srv)
}

func _HomeService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeService_WatchDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HomeServiceServer).WatchDevices(m, &grpc.GenericServerStream[WatchDevicesRequest, DeviceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomeService_WatchDevicesServer = grpc.ServerStreamingServer[DeviceEvent]

func _HomeService_UpsertDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServiceServer).UpsertDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeService_UpsertDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServiceServer).UpsertDevice(ctx, req.(*UpsertDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeService_ReserveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServiceServer).ReserveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeService_ReserveDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServiceServer).ReserveDevice(ctx, req.(*ReserveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeService_DeleteDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeService_InvokeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServiceServer).InvokeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeService_InvokeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServiceServer).InvokeAction(ctx, req.(*InvokeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HomeService_ServiceDesc is the grpc.ServiceDesc for HomeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HomeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control.home.HomeService",
	HandlerType: (*HomeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _HomeService_ListDevices_Handler,
		},
		{
			MethodName: "UpsertDevice",
			Handler:    _HomeService_UpsertDevice_Handler,
		},
		{
			MethodName: "ReserveDevice",
			Handler:    _HomeService_ReserveDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _HomeService_DeleteDevice_Handler,
		},
		{
			MethodName: "InvokeAction",
			Handler:    _HomeService_InvokeAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchDevices",
			Handler:       _HomeService_WatchDevices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "home/service.proto",
}

const (
	AuditService_ListLogs_FullMethodName    = "/remote_control.home.AuditService/ListLogs"
	AuditService_CleanupLogs_FullMethodName = "/remote_control.home.AuditService/CleanupLogs"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	ListLogs(ctx context.Context, in *ListLogsRequest, opts ...grpc.CallOption) (*ListLogsResponse, error)
	CleanupLogs(ctx context.Context, in *CleanupLogsRequest, opts ...grpc.CallOption) (*CleanupLogsResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) ListLogs(ctx context.Context, in *ListLogsRequest, opts ...grpc.CallOption) (*ListLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLogsResponse)
	err := c.cc.Invoke(ctx, AuditService_ListLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) CleanupLogs(ctx context.Context, in *CleanupLogsRequest, opts ...grpc.CallOption) (*CleanupLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupLogsResponse)
	err := c.cc.Invoke(ctx, AuditService_CleanupLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	ListLogs(context.Context, *ListLogsRequest) (*ListLogsResponse, error)
	CleanupLogs(context.Context, *CleanupLogsRequest) (*CleanupLogsResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) ListLogs(context.Context, *ListLogsRequest) (*ListLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLogs not implemented")
}
func (UnimplementedAuditServiceServer) CleanupLogs(context.Context, *CleanupLogsRequest) (*CleanupLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanupLogs not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_ListLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListLogs(ctx, req.(*ListLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_CleanupLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).CleanupLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_CleanupLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).CleanupLogs(ctx, req.(*CleanupLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control.home.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLogs",
			Handler:    _AuditService_ListLogs_Handler,
		},
		{
			MethodName: "CleanupLogs",
			Handler:    _AuditService_CleanupLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "home/service.proto",
}

const (
	AutomationService_ListAutomations_FullMethodName      = "/remote_control.home.AutomationService/ListAutomations"
	AutomationService_UpsertAutomation_FullMethodName     = "/remote_control.home.AutomationService/UpsertAutomation"
	AutomationService_DeleteAutomation_FullMethodName     = "/remote_control.home.AutomationService/DeleteAutomation"
	AutomationService_SetAutomationEnabled_FullMethodName = "/remote_control.home.AutomationService/SetAutomationEnabled"
	AutomationService_TriggerAutomation_FullMethodName    = "/remote_control.home.AutomationService/TriggerAutomation"
)

// AutomationServiceClient is the client API for AutomationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationServiceClient interface {
	ListAutomations(ctx context.Context, in *ListAutomationsRequest, opts ...grpc.CallOption) (*ListAutomationsResponse, error)
	UpsertAutomation(ctx context.Context, in *UpsertAutomationRequest, opts ...grpc.CallOption) (*UpsertAutomationResponse, error)
	DeleteAutomation(ctx context.Context, in *DeleteAutomationRequest, opts ...grpc.CallOption) (*DeleteAutomationResponse, error)
	SetAutomationEnabled(ctx context.Context, in *SetAutomationEnabledRequest, opts ...grpc.CallOption) (*SetAutomationEnabledResponse, error)
	TriggerAutomation(ctx context.Context, in *TriggerAutomationRequest, opts ...grpc.CallOption) (*TriggerAutomationResponse, error)
}

type automationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationServiceClient(cc grpc.ClientConnInterface) AutomationServiceClient {
	return &automationServiceClient{cc}
}

func (c *automationServiceClient) ListAutomations(ctx context.Context, in *ListAutomationsRequest, opts ...grpc.CallOption) (*ListAutomationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAutomationsResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListAutomations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) UpsertAutomation(ctx context.Context, in *UpsertAutomationRequest, opts ...grpc.CallOption) (*UpsertAutomationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertAutomationResponse)
	err := c.cc.Invoke(ctx, AutomationService_UpsertAutomation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) DeleteAutomation(ctx context.Context, in *DeleteAutomationRequest, opts ...grpc.CallOption) (*DeleteAutomationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAutomationResponse)
	err := c.cc.Invoke(ctx, AutomationService_DeleteAutomation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) SetAutomationEnabled(ctx context.Context, in *SetAutomationEnabledRequest, opts ...grpc.CallOption) (*SetAutomationEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAutomationEnabledResponse)
	err := c.cc.Invoke(ctx, AutomationService_SetAutomationEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) TriggerAutomation(ctx context.Context, in *TriggerAutomationRequest, opts ...grpc.CallOption) (*TriggerAutomationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerAutomationResponse)
	err := c.cc.Invoke(ctx, AutomationService_TriggerAutomation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationServiceServer is the server API for AutomationService service.
// All implementations must embed UnimplementedAutomationServiceServer
// for forward compatibility.
type AutomationServiceServer interface {
	ListAutomations(context.Context, *ListAutomationsRequest) (*ListAutomationsResponse, error)
	UpsertAutomation(context.Context, *UpsertAutomationRequest) (*UpsertAutomationResponse, error)
	DeleteAutomation(context.Context, *DeleteAutomationRequest) (*DeleteAutomationResponse, error)
	SetAutomationEnabled(context.Context, *SetAutomationEnabledRequest) (*SetAutomationEnabledResponse, error)
	TriggerAutomation(context.Context, *TriggerAutomationRequest) (*TriggerAutomationResponse, error)
	mustEmbedUnimplementedAutomationServiceServer()
}

// UnimplementedAutomationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationServiceServer struct{}

func (UnimplementedAutomationServiceServer) ListAutomations(context.Context, *ListAutomationsRequest) (*ListAutomationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAutomations not implemented")
}
func (UnimplementedAutomationServiceServer) UpsertAutomation(context.Context, *UpsertAutomationRequest) (*UpsertAutomationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertAutomation not implemented")
}
func (UnimplementedAutomationServiceServer) DeleteAutomation(context.Context, *DeleteAutomationRequest) (*DeleteAutomationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAutomation not implemented")
}
func (UnimplementedAutomationServiceServer) SetAutomationEnabled(context.Context, *SetAutomationEnabledRequest) (*SetAutomationEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAutomationEnabled not implemented")
}
func (UnimplementedAutomationServiceServer) TriggerAutomation(context.Context, *TriggerAutomationRequest) (*TriggerAutomationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerAutomation not implemented")
}
func (UnimplementedAutomationServiceServer) mustEmbedUnimplementedAutomationServiceServer() {}
func (UnimplementedAutomationServiceServer) testEmbeddedByValue()                           {}

// UnsafeAutomationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationServiceServer will
// result in compilation errors.
type UnsafeAutomationServiceServer interface {
	mustEmbedUnimplementedAutomationServiceServer()
}

func RegisterAutomationServiceServer(s grpc.ServiceRegistrar, srv AutomationServiceServer) {
	// If the following call pancis, it indicates UnimplementedAutomationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationService_ServiceDesc, srv)
}

func _AutomationService_ListAutomations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAutomationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListAutomations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListAutomations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListAutomations(ctx, req.(*ListAutomationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_UpsertAutomation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAutomationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).UpsertAutomation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_UpsertAutomation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).UpsertAutomation(ctx, req.(*UpsertAutomationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_DeleteAutomation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAutomationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).DeleteAutomation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_DeleteAutomation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).DeleteAutomation(ctx, req.(*DeleteAutomationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_SetAutomationEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutomationEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).SetAutomationEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_SetAutomationEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).SetAutomationEnabled(ctx, req.(*SetAutomationEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_TriggerAutomation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerAutomationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).TriggerAutomation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_TriggerAutomation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).TriggerAutomation(ctx, req.(*TriggerAutomationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationService_ServiceDesc is the grpc.ServiceDesc for AutomationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control.home.AutomationService",
	HandlerType: (*AutomationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAutomations",
			Handler:    _AutomationService_ListAutomations_Handler,
		},
		{
			MethodName: "UpsertAutomation",
			Handler:    _AutomationService_UpsertAutomation_Handler,
		},
		{
			MethodName: "DeleteAutomation",
			Handler:    _AutomationService_DeleteAutomation_Handler,
		},
		{
			MethodName: "SetAutomationEnabled",
			Handler:    _AutomationService_SetAutomationEnabled_Handler,
		},
		{
			MethodName: "TriggerAutomation",
			Handler:    _AutomationService_TriggerAutomation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "home/service.proto",
}

const (
	DeviceModelService_ListDeviceModels_FullMethodName  = "/remote_control.home.DeviceModelService/ListDeviceModels"
	DeviceModelService_GetDeviceModel_FullMethodName    = "/remote_control.home.DeviceModelService/GetDeviceModel"
	DeviceModelService_CreateDeviceModel_FullMethodName = "/remote_control.home.DeviceModelService/CreateDeviceModel"
	DeviceModelService_UpdateDeviceModel_FullMethodName = "/remote_control.home.DeviceModelService/UpdateDeviceModel"
	DeviceModelService_DeleteDeviceModel_FullMethodName = "/remote_control.home.DeviceModelService/DeleteDeviceModel"
)

// DeviceModelServiceClient is the client API for DeviceModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceModelServiceClient interface {
	ListDeviceModels(ctx context.Context, in *ListDeviceModelsRequest, opts ...grpc.CallOption) (*ListDeviceModelsResponse, error)
	GetDeviceModel(ctx context.Context, in *GetDeviceModelRequest, opts ...grpc.CallOption) (*GetDeviceModelResponse, error)
	CreateDeviceModel(ctx context.Context, in *CreateDeviceModelRequest, opts ...grpc.CallOption) (*CreateDeviceModelResponse, error)
	UpdateDeviceModel(ctx context.Context, in *UpdateDeviceModelRequest, opts ...grpc.CallOption) (*UpdateDeviceModelResponse, error)
	DeleteDeviceModel(ctx context.Context, in *DeleteDeviceModelRequest, opts ...grpc.CallOption) (*DeleteDeviceModelResponse, error)
}

type deviceModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceModelServiceClient(cc grpc.ClientConnInterface) DeviceModelServiceClient {
	return &deviceModelServiceClient{cc}
}

func (c *deviceModelServiceClient) ListDeviceModels(ctx context.Context, in *ListDeviceModelsRequest, opts ...grpc.CallOption) (*ListDeviceModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeviceModelsResponse)
	err := c.cc.Invoke(ctx, DeviceModelService_ListDeviceModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceModelServiceClient) GetDeviceModel(ctx context.Context, in *GetDeviceModelRequest, opts ...grpc.CallOption) (*GetDeviceModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceModelResponse)
	err := c.cc.Invoke(ctx, DeviceModelService_GetDeviceModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceModelServiceClient) CreateDeviceModel(ctx context.Context, in *CreateDeviceModelRequest, opts ...grpc.CallOption) (*CreateDeviceModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeviceModelResponse)
	err := c.cc.Invoke(ctx, DeviceModelService_CreateDeviceModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceModelServiceClient) UpdateDeviceModel(ctx context.Context, in *UpdateDeviceModelRequest, opts ...grpc.CallOption) (*UpdateDeviceModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeviceModelResponse)
	err := c.cc.Invoke(ctx, DeviceModelService_UpdateDeviceModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceModelServiceClient) DeleteDeviceModel(ctx context.Context, in *DeleteDeviceModelRequest, opts ...grpc.CallOption) (*DeleteDeviceModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeviceModelResponse)
	err := c.cc.Invoke(ctx, DeviceModelService_DeleteDeviceModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceModelServiceServer is the server API for DeviceModelService service.
// All implementations must embed UnimplementedDeviceModelServiceServer
// for forward compatibility.
type DeviceModelServiceServer interface {
	ListDeviceModels(context.Context, *ListDeviceModelsRequest) (*ListDeviceModelsResponse, error)
	GetDeviceModel(context.Context, *GetDeviceModelRequest) (*GetDeviceModelResponse, error)
	CreateDeviceModel(context.Context, *CreateDeviceModelRequest) (*CreateDeviceModelResponse, error)
	UpdateDeviceModel(context.Context, *UpdateDeviceModelRequest) (*UpdateDeviceModelResponse, error)
	DeleteDeviceModel(context.Context, *DeleteDeviceModelRequest) (*DeleteDeviceModelResponse, error)
	mustEmbedUnimplementedDeviceModelServiceServer()
}

// UnimplementedDeviceModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceModelServiceServer struct{}

func (UnimplementedDeviceModelServiceServer) ListDeviceModels(context.Context, *ListDeviceModelsRequest) (*ListDeviceModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeviceModels not implemented")
}
func (UnimplementedDeviceModelServiceServer) GetDeviceModel(context.Context, *GetDeviceModelRequest) (*GetDeviceModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceModel not implemented")
}
func (UnimplementedDeviceModelServiceServer) CreateDeviceModel(context.Context, *CreateDeviceModelRequest) (*CreateDeviceModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeviceModel not implemented")
}
func (UnimplementedDeviceModelServiceServer) UpdateDeviceModel(context.Context, *UpdateDeviceModelRequest) (*UpdateDeviceModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeviceModel not implemented")
}
func (UnimplementedDeviceModelServiceServer) DeleteDeviceModel(context.Context, *DeleteDeviceModelRequest) (*DeleteDeviceModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeviceModel not implemented")
}
func (UnimplementedDeviceModelServiceServer) mustEmbedUnimplementedDeviceModelServiceServer() {}
func (UnimplementedDeviceModelServiceServer) testEmbeddedByValue()                            {}

// UnsafeDeviceModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceModelServiceServer will
// result in compilation errors.
type UnsafeDeviceModelServiceServer interface {
	mustEmbedUnimplementedDeviceModelServiceServer()
}

func RegisterDeviceModelServiceServer(s grpc.ServiceRegistrar, srv DeviceModelServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeviceModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceModelService_ServiceDesc, srv)
}

func _DeviceModelService_ListDeviceModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceModelServiceServer).ListDeviceModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceModelService_ListDeviceModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceModelServiceServer).ListDeviceModels(ctx, req.(*ListDeviceModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceModelService_GetDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceModelServiceServer).GetDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceModelService_GetDeviceModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceModelServiceServer).GetDeviceModel(ctx, req.(*GetDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceModelService_CreateDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceModelServiceServer).CreateDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceModelService_CreateDeviceModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceModelServiceServer).CreateDeviceModel(ctx, req.(*CreateDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceModelService_UpdateDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceModelServiceServer).UpdateDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceModelService_UpdateDeviceModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceModelServiceServer).UpdateDeviceModel(ctx, req.(*UpdateDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceModelService_DeleteDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceModelServiceServer).DeleteDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceModelService_DeleteDeviceModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceModelServiceServer).DeleteDeviceModel(ctx, req.(*DeleteDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceModelService_ServiceDesc is the grpc.ServiceDesc for DeviceModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control.home.DeviceModelService",
	HandlerType: (*DeviceModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeviceModels",
			Handler:    _DeviceModelService_ListDeviceModels_Handler,
		},
		{
			MethodName: "GetDeviceModel",
			Handler:    _DeviceModelService_GetDeviceModel_Handler,
		},
		{
			MethodName: "CreateDeviceModel",
			Handler:    _DeviceModelService_CreateDeviceModel_Handler,
		},
		{
			MethodName: "UpdateDeviceModel",
			Handler:    _DeviceModelService_UpdateDeviceModel_Handler,
		},
		{
			MethodName: "DeleteDeviceModel",
			Handler:    _DeviceModelService_DeleteDeviceModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "home/service.proto",
}

const (
	CloudConfigService_ListCloudConfigs_FullMethodName  = "/remote_control.home.CloudConfigService/ListCloudConfigs"
	CloudConfigService_UpsertCloudConfig_FullMethodName = "/remote_control.home.CloudConfigService/UpsertCloudConfig"
	CloudConfigService_DeleteCloudConfig_FullMethodName = "/remote_control.home.CloudConfigService/DeleteCloudConfig"
	CloudConfigService_ApplyCloudConfig_FullMethodName  = "/remote_control.home.CloudConfigService/ApplyCloudConfig"
)

// CloudConfigServiceClient is the client API for CloudConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudConfigServiceClient interface {
	ListCloudConfigs(ctx context.Context, in *ListCloudConfigsRequest, opts ...grpc.CallOption) (*ListCloudConfigsResponse, error)
	UpsertCloudConfig(ctx context.Context, in *UpsertCloudConfigRequest, opts ...grpc.CallOption) (*UpsertCloudConfigResponse, error)
	DeleteCloudConfig(ctx context.Context, in *DeleteCloudConfigRequest, opts ...grpc.CallOption) (*DeleteCloudConfigResponse, error)
	ApplyCloudConfig(ctx context.Context, in *ApplyCloudConfigRequest, opts ...grpc.CallOption) (*ApplyCloudConfigResponse, error)
}

type cloudConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudConfigServiceClient(cc grpc.ClientConnInterface) CloudConfigServiceClient {
	return &cloudConfigServiceClient{cc}
}

func (c *cloudConfigServiceClient) ListCloudConfigs(ctx context.Context, in *ListCloudConfigsRequest, opts ...grpc.CallOption) (*ListCloudConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCloudConfigsResponse)
	err := c.cc.Invoke(ctx, CloudConfigService_ListCloudConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudConfigServiceClient) UpsertCloudConfig(ctx context.Context, in *UpsertCloudConfigRequest, opts ...grpc.CallOption) (*UpsertCloudConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertCloudConfigResponse)
	err := c.cc.Invoke(ctx, CloudConfigService_UpsertCloudConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudConfigServiceClient) DeleteCloudConfig(ctx context.Context, in *DeleteCloudConfigRequest, opts ...grpc.CallOption) (*DeleteCloudConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCloudConfigResponse)
	err := c.cc.Invoke(ctx, CloudConfigService_DeleteCloudConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudConfigServiceClient) ApplyCloudConfig(ctx context.Context, in *ApplyCloudConfigRequest, opts ...grpc.CallOption) (*ApplyCloudConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCloudConfigResponse)
	err := c.cc.Invoke(ctx, CloudConfigService_ApplyCloudConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudConfigServiceServer is the server API for CloudConfigService service.
// All implementations must embed UnimplementedCloudConfigServiceServer
// for forward compatibility.
type CloudConfigServiceServer interface {
	ListCloudConfigs(context.Context, *ListCloudConfigsRequest) (*ListCloudConfigsResponse, error)
	UpsertCloudConfig(context.Context, *UpsertCloudConfigRequest) (*UpsertCloudConfigResponse, error)
	DeleteCloudConfig(context.Context, *DeleteCloudConfigRequest) (*DeleteCloudConfigResponse, error)
	ApplyCloudConfig(context.Context, *ApplyCloudConfigRequest) (*ApplyCloudConfigResponse, error)
	mustEmbedUnimplementedCloudConfigServiceServer()
}

// UnimplementedCloudConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudConfigServiceServer struct{}

func (UnimplementedCloudConfigServiceServer) ListCloudConfigs(context.Context, *ListCloudConfigsRequest) (*ListCloudConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCloudConfigs not implemented")
}
func (UnimplementedCloudConfigServiceServer) UpsertCloudConfig(context.Context, *UpsertCloudConfigRequest) (*UpsertCloudConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCloudConfig not implemented")
}
func (UnimplementedCloudConfigServiceServer) DeleteCloudConfig(context.Context, *DeleteCloudConfigRequest) (*DeleteCloudConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCloudConfig not implemented")
}
func (UnimplementedCloudConfigServiceServer) ApplyCloudConfig(context.Context, *ApplyCloudConfigRequest) (*ApplyCloudConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyCloudConfig not implemented")
}
func (UnimplementedCloudConfigServiceServer) mustEmbedUnimplementedCloudConfigServiceServer() {}
func (UnimplementedCloudConfigServiceServer) testEmbeddedByValue()                            {}

// UnsafeCloudConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudConfigServiceServer will
// result in compilation errors.
type UnsafeCloudConfigServiceServer interface {
	mustEmbedUnimplementedCloudConfigServiceServer()
}

func RegisterCloudConfigServiceServer(s grpc.ServiceRegistrar, srv CloudConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedCloudConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudConfigService_ServiceDesc, srv)
}

func _CloudConfigService_ListCloudConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCloudConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudConfigServiceServer).ListCloudConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudConfigService_ListCloudConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudConfigServiceServer).ListCloudConfigs(ctx, req.(*ListCloudConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudConfigService_UpsertCloudConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCloudConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudConfigServiceServer).UpsertCloudConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudConfigService_UpsertCloudConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudConfigServiceServer).UpsertCloudConfig(ctx, req.(*UpsertCloudConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudConfigService_DeleteCloudConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCloudConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudConfigServiceServer).DeleteCloudConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudConfigService_DeleteCloudConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudConfigServiceServer).DeleteCloudConfig(ctx, req.(*DeleteCloudConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudConfigService_ApplyCloudConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCloudConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudConfigServiceServer).ApplyCloudConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudConfigService_ApplyCloudConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudConfigServiceServer).ApplyCloudConfig(ctx, req.(*ApplyCloudConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudConfigService_ServiceDesc is the grpc.ServiceDesc for CloudConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control.home.CloudConfigService",
	HandlerType: (*CloudConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCloudConfigs",
			Handler:    _CloudConfigService_ListCloudConfigs_Handler,
		},
		{
			MethodName: "UpsertCloudConfig",
			Handler:    _CloudConfigService_UpsertCloudConfig_Handler,
		},
		{
			MethodName: "DeleteCloudConfig",
			Handler:    _CloudConfigService_DeleteCloudConfig_Handler,
		},
		{
			MethodName: "ApplyCloudConfig",
			Handler:    _CloudConfigService_ApplyCloudConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "home/service.proto",
}
