// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "home/service.proto" (package "remote_control.home", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Struct } from "../google/protobuf/struct";
/**
 * @generated from protobuf message remote_control.home.Adapter
 */
export interface Adapter {
    /**
     * @generated from protobuf field: remote_control.home.AdapterKind kind = 1
     */
    kind: AdapterKind;
    /**
     * @generated from protobuf field: map<string, string> config = 2
     */
    config: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf message remote_control.home.ActionSpec
 */
export interface ActionSpec {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: map<string, string> args_schema = 2
     */
    argsSchema: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: int32 timeout_ms = 3
     */
    timeoutMs: number;
}
/**
 * @generated from protobuf message remote_control.home.Device
 */
export interface Device {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string type = 3
     */
    type: string;
    /**
     * @generated from protobuf field: string room = 4
     */
    room: string;
    /**
     * @generated from protobuf field: repeated string tags = 5
     */
    tags: string[];
    /**
     * @generated from protobuf field: bool online = 6
     */
    online: boolean;
    /**
     * @generated from protobuf field: int64 last_seen = 7
     */
    lastSeen: string;
    /**
     * @generated from protobuf field: map<string, string> topics = 8
     */
    topics: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: remote_control.home.Adapter adapter = 9
     */
    adapter?: Adapter;
    /**
     * @generated from protobuf field: repeated remote_control.home.ActionSpec actions = 10
     */
    actions: ActionSpec[];
    /**
     * @generated from protobuf field: google.protobuf.Struct state = 11
     */
    state?: Struct;
}
/**
 * @generated from protobuf message remote_control.home.ListDevicesRequest
 */
export interface ListDevicesRequest {
    /**
     * @generated from protobuf field: repeated string ids = 1
     */
    ids: string[];
    /**
     * @generated from protobuf field: string type = 2
     */
    type: string;
    /**
     * @generated from protobuf field: string room = 3
     */
    room: string;
    /**
     * @generated from protobuf field: repeated string tags = 4
     */
    tags: string[];
    /**
     * @generated from protobuf field: bool include_state = 5
     */
    includeState: boolean;
}
/**
 * @generated from protobuf message remote_control.home.ListDevicesResponse
 */
export interface ListDevicesResponse {
    /**
     * @generated from protobuf field: repeated remote_control.home.Device devices = 1
     */
    devices: Device[];
}
/**
 * @generated from protobuf message remote_control.home.WatchDevicesRequest
 */
export interface WatchDevicesRequest {
    /**
     * @generated from protobuf field: repeated string ids = 1
     */
    ids: string[]; // empty for all
}
/**
 * @generated from protobuf message remote_control.home.DeviceEvent
 */
export interface DeviceEvent {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: int64 ts = 2
     */
    ts: string;
    /**
     * @generated from protobuf field: remote_control.home.TelemetryEventKind kind = 3
     */
    kind: TelemetryEventKind;
    /**
     * @generated from protobuf field: google.protobuf.Struct payload = 4
     */
    payload?: Struct;
}
/**
 * @generated from protobuf message remote_control.home.UpsertDeviceRequest
 */
export interface UpsertDeviceRequest {
    /**
     * @generated from protobuf field: remote_control.home.Device device = 1
     */
    device?: Device;
}
/**
 * @generated from protobuf message remote_control.home.UpsertDeviceResponse
 */
export interface UpsertDeviceResponse {
    /**
     * @generated from protobuf field: bool ok = 1
     */
    ok: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message remote_control.home.DeleteDeviceRequest
 */
export interface DeleteDeviceRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
}
/**
 * @generated from protobuf message remote_control.home.DeleteDeviceResponse
 */
export interface DeleteDeviceResponse {
    /**
     * @generated from protobuf field: bool ok = 1
     */
    ok: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message remote_control.home.InvokeActionRequest
 */
export interface InvokeActionRequest {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string action = 2
     */
    action: string;
    /**
     * @generated from protobuf field: google.protobuf.Struct args = 3
     */
    args?: Struct;
    /**
     * @generated from protobuf field: int32 timeout_ms = 4
     */
    timeoutMs: number;
}
/**
 * @generated from protobuf message remote_control.home.InvokeActionResponse
 */
export interface InvokeActionResponse {
    /**
     * @generated from protobuf field: bool ok = 1
     */
    ok: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: string corr_id = 3
     */
    corrId: string;
    /**
     * @generated from protobuf field: google.protobuf.Struct data = 4
     */
    data?: Struct;
}
/**
 * @generated from protobuf enum remote_control.home.AdapterKind
 */
export enum AdapterKind {
    /**
     * @generated from protobuf enum value: ADAPTER_KIND_UNSPECIFIED = 0;
     */
    ADAPTER_KIND_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: MQTT = 1;
     */
    MQTT = 1,
    /**
     * @generated from protobuf enum value: SERIAL = 2;
     */
    SERIAL = 2,
    /**
     * @generated from protobuf enum value: HTTP = 3;
     */
    HTTP = 3
}
/**
 * @generated from protobuf enum remote_control.home.TelemetryEventKind
 */
export enum TelemetryEventKind {
    /**
     * @generated from protobuf enum value: EVENT_KIND_UNSPECIFIED = 0;
     */
    EVENT_KIND_UNSPECIFIED = 0,
    /**
     * device state update
     *
     * @generated from protobuf enum value: STATE = 1;
     */
    STATE = 1,
    /**
     * online/offline status
     *
     * @generated from protobuf enum value: ONLINE = 2;
     */
    ONLINE = 2,
    /**
     * action execution result
     *
     * @generated from protobuf enum value: ACTION_RESULT = 3;
     */
    ACTION_RESULT = 3,
    /**
     * custom event
     *
     * @generated from protobuf enum value: EVENT = 4;
     */
    EVENT = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class Adapter$Type extends MessageType<Adapter> {
    constructor() {
        super("remote_control.home.Adapter", [
            { no: 1, name: "kind", kind: "enum", T: () => ["remote_control.home.AdapterKind", AdapterKind] },
            { no: 2, name: "config", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<Adapter>): Adapter {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = 0;
        message.config = {};
        if (value !== undefined)
            reflectionMergePartial<Adapter>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Adapter): Adapter {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* remote_control.home.AdapterKind kind */ 1:
                    message.kind = reader.int32();
                    break;
                case /* map<string, string> config */ 2:
                    this.binaryReadMap2(message.config, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: Adapter["config"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof Adapter["config"] | undefined, val: Adapter["config"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for remote_control.home.Adapter.config");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: Adapter, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* remote_control.home.AdapterKind kind = 1; */
        if (message.kind !== 0)
            writer.tag(1, WireType.Varint).int32(message.kind);
        /* map<string, string> config = 2; */
        for (let k of globalThis.Object.keys(message.config))
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.config[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.Adapter
 */
export const Adapter = new Adapter$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ActionSpec$Type extends MessageType<ActionSpec> {
    constructor() {
        super("remote_control.home.ActionSpec", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "args_schema", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 3, name: "timeout_ms", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ActionSpec>): ActionSpec {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.argsSchema = {};
        message.timeoutMs = 0;
        if (value !== undefined)
            reflectionMergePartial<ActionSpec>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ActionSpec): ActionSpec {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* map<string, string> args_schema */ 2:
                    this.binaryReadMap2(message.argsSchema, reader, options);
                    break;
                case /* int32 timeout_ms */ 3:
                    message.timeoutMs = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: ActionSpec["argsSchema"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof ActionSpec["argsSchema"] | undefined, val: ActionSpec["argsSchema"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for remote_control.home.ActionSpec.args_schema");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: ActionSpec, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* map<string, string> args_schema = 2; */
        for (let k of globalThis.Object.keys(message.argsSchema))
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.argsSchema[k]).join();
        /* int32 timeout_ms = 3; */
        if (message.timeoutMs !== 0)
            writer.tag(3, WireType.Varint).int32(message.timeoutMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.ActionSpec
 */
export const ActionSpec = new ActionSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Device$Type extends MessageType<Device> {
    constructor() {
        super("remote_control.home.Device", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "room", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "tags", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "online", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "last_seen", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "topics", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 9, name: "adapter", kind: "message", T: () => Adapter },
            { no: 10, name: "actions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ActionSpec },
            { no: 11, name: "state", kind: "message", T: () => Struct }
        ]);
    }
    create(value?: PartialMessage<Device>): Device {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.type = "";
        message.room = "";
        message.tags = [];
        message.online = false;
        message.lastSeen = "0";
        message.topics = {};
        message.actions = [];
        if (value !== undefined)
            reflectionMergePartial<Device>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Device): Device {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string type */ 3:
                    message.type = reader.string();
                    break;
                case /* string room */ 4:
                    message.room = reader.string();
                    break;
                case /* repeated string tags */ 5:
                    message.tags.push(reader.string());
                    break;
                case /* bool online */ 6:
                    message.online = reader.bool();
                    break;
                case /* int64 last_seen */ 7:
                    message.lastSeen = reader.int64().toString();
                    break;
                case /* map<string, string> topics */ 8:
                    this.binaryReadMap8(message.topics, reader, options);
                    break;
                case /* remote_control.home.Adapter adapter */ 9:
                    message.adapter = Adapter.internalBinaryRead(reader, reader.uint32(), options, message.adapter);
                    break;
                case /* repeated remote_control.home.ActionSpec actions */ 10:
                    message.actions.push(ActionSpec.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* google.protobuf.Struct state */ 11:
                    message.state = Struct.internalBinaryRead(reader, reader.uint32(), options, message.state);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap8(map: Device["topics"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof Device["topics"] | undefined, val: Device["topics"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for remote_control.home.Device.topics");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: Device, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string type = 3; */
        if (message.type !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.type);
        /* string room = 4; */
        if (message.room !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.room);
        /* repeated string tags = 5; */
        for (let i = 0; i < message.tags.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.tags[i]);
        /* bool online = 6; */
        if (message.online !== false)
            writer.tag(6, WireType.Varint).bool(message.online);
        /* int64 last_seen = 7; */
        if (message.lastSeen !== "0")
            writer.tag(7, WireType.Varint).int64(message.lastSeen);
        /* map<string, string> topics = 8; */
        for (let k of globalThis.Object.keys(message.topics))
            writer.tag(8, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.topics[k]).join();
        /* remote_control.home.Adapter adapter = 9; */
        if (message.adapter)
            Adapter.internalBinaryWrite(message.adapter, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* repeated remote_control.home.ActionSpec actions = 10; */
        for (let i = 0; i < message.actions.length; i++)
            ActionSpec.internalBinaryWrite(message.actions[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Struct state = 11; */
        if (message.state)
            Struct.internalBinaryWrite(message.state, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.Device
 */
export const Device = new Device$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListDevicesRequest$Type extends MessageType<ListDevicesRequest> {
    constructor() {
        super("remote_control.home.ListDevicesRequest", [
            { no: 1, name: "ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "room", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tags", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "include_state", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ListDevicesRequest>): ListDevicesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ids = [];
        message.type = "";
        message.room = "";
        message.tags = [];
        message.includeState = false;
        if (value !== undefined)
            reflectionMergePartial<ListDevicesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListDevicesRequest): ListDevicesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string ids */ 1:
                    message.ids.push(reader.string());
                    break;
                case /* string type */ 2:
                    message.type = reader.string();
                    break;
                case /* string room */ 3:
                    message.room = reader.string();
                    break;
                case /* repeated string tags */ 4:
                    message.tags.push(reader.string());
                    break;
                case /* bool include_state */ 5:
                    message.includeState = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListDevicesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string ids = 1; */
        for (let i = 0; i < message.ids.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.ids[i]);
        /* string type = 2; */
        if (message.type !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.type);
        /* string room = 3; */
        if (message.room !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.room);
        /* repeated string tags = 4; */
        for (let i = 0; i < message.tags.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.tags[i]);
        /* bool include_state = 5; */
        if (message.includeState !== false)
            writer.tag(5, WireType.Varint).bool(message.includeState);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.ListDevicesRequest
 */
export const ListDevicesRequest = new ListDevicesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListDevicesResponse$Type extends MessageType<ListDevicesResponse> {
    constructor() {
        super("remote_control.home.ListDevicesResponse", [
            { no: 1, name: "devices", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Device }
        ]);
    }
    create(value?: PartialMessage<ListDevicesResponse>): ListDevicesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.devices = [];
        if (value !== undefined)
            reflectionMergePartial<ListDevicesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListDevicesResponse): ListDevicesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated remote_control.home.Device devices */ 1:
                    message.devices.push(Device.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListDevicesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated remote_control.home.Device devices = 1; */
        for (let i = 0; i < message.devices.length; i++)
            Device.internalBinaryWrite(message.devices[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.ListDevicesResponse
 */
export const ListDevicesResponse = new ListDevicesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WatchDevicesRequest$Type extends MessageType<WatchDevicesRequest> {
    constructor() {
        super("remote_control.home.WatchDevicesRequest", [
            { no: 1, name: "ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WatchDevicesRequest>): WatchDevicesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ids = [];
        if (value !== undefined)
            reflectionMergePartial<WatchDevicesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WatchDevicesRequest): WatchDevicesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string ids */ 1:
                    message.ids.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WatchDevicesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string ids = 1; */
        for (let i = 0; i < message.ids.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.ids[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.WatchDevicesRequest
 */
export const WatchDevicesRequest = new WatchDevicesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeviceEvent$Type extends MessageType<DeviceEvent> {
    constructor() {
        super("remote_control.home.DeviceEvent", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ts", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "kind", kind: "enum", T: () => ["remote_control.home.TelemetryEventKind", TelemetryEventKind] },
            { no: 4, name: "payload", kind: "message", T: () => Struct }
        ]);
    }
    create(value?: PartialMessage<DeviceEvent>): DeviceEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.ts = "0";
        message.kind = 0;
        if (value !== undefined)
            reflectionMergePartial<DeviceEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeviceEvent): DeviceEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* int64 ts */ 2:
                    message.ts = reader.int64().toString();
                    break;
                case /* remote_control.home.TelemetryEventKind kind */ 3:
                    message.kind = reader.int32();
                    break;
                case /* google.protobuf.Struct payload */ 4:
                    message.payload = Struct.internalBinaryRead(reader, reader.uint32(), options, message.payload);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeviceEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* int64 ts = 2; */
        if (message.ts !== "0")
            writer.tag(2, WireType.Varint).int64(message.ts);
        /* remote_control.home.TelemetryEventKind kind = 3; */
        if (message.kind !== 0)
            writer.tag(3, WireType.Varint).int32(message.kind);
        /* google.protobuf.Struct payload = 4; */
        if (message.payload)
            Struct.internalBinaryWrite(message.payload, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.DeviceEvent
 */
export const DeviceEvent = new DeviceEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpsertDeviceRequest$Type extends MessageType<UpsertDeviceRequest> {
    constructor() {
        super("remote_control.home.UpsertDeviceRequest", [
            { no: 1, name: "device", kind: "message", T: () => Device }
        ]);
    }
    create(value?: PartialMessage<UpsertDeviceRequest>): UpsertDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpsertDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpsertDeviceRequest): UpsertDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* remote_control.home.Device device */ 1:
                    message.device = Device.internalBinaryRead(reader, reader.uint32(), options, message.device);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpsertDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* remote_control.home.Device device = 1; */
        if (message.device)
            Device.internalBinaryWrite(message.device, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.UpsertDeviceRequest
 */
export const UpsertDeviceRequest = new UpsertDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpsertDeviceResponse$Type extends MessageType<UpsertDeviceResponse> {
    constructor() {
        super("remote_control.home.UpsertDeviceResponse", [
            { no: 1, name: "ok", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpsertDeviceResponse>): UpsertDeviceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ok = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<UpsertDeviceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpsertDeviceResponse): UpsertDeviceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool ok */ 1:
                    message.ok = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpsertDeviceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool ok = 1; */
        if (message.ok !== false)
            writer.tag(1, WireType.Varint).bool(message.ok);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.UpsertDeviceResponse
 */
export const UpsertDeviceResponse = new UpsertDeviceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteDeviceRequest$Type extends MessageType<DeleteDeviceRequest> {
    constructor() {
        super("remote_control.home.DeleteDeviceRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteDeviceRequest>): DeleteDeviceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteDeviceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteDeviceRequest): DeleteDeviceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteDeviceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.DeleteDeviceRequest
 */
export const DeleteDeviceRequest = new DeleteDeviceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteDeviceResponse$Type extends MessageType<DeleteDeviceResponse> {
    constructor() {
        super("remote_control.home.DeleteDeviceResponse", [
            { no: 1, name: "ok", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteDeviceResponse>): DeleteDeviceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ok = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteDeviceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteDeviceResponse): DeleteDeviceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool ok */ 1:
                    message.ok = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteDeviceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool ok = 1; */
        if (message.ok !== false)
            writer.tag(1, WireType.Varint).bool(message.ok);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.DeleteDeviceResponse
 */
export const DeleteDeviceResponse = new DeleteDeviceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InvokeActionRequest$Type extends MessageType<InvokeActionRequest> {
    constructor() {
        super("remote_control.home.InvokeActionRequest", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "action", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "args", kind: "message", T: () => Struct },
            { no: 4, name: "timeout_ms", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<InvokeActionRequest>): InvokeActionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.action = "";
        message.timeoutMs = 0;
        if (value !== undefined)
            reflectionMergePartial<InvokeActionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InvokeActionRequest): InvokeActionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* string action */ 2:
                    message.action = reader.string();
                    break;
                case /* google.protobuf.Struct args */ 3:
                    message.args = Struct.internalBinaryRead(reader, reader.uint32(), options, message.args);
                    break;
                case /* int32 timeout_ms */ 4:
                    message.timeoutMs = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InvokeActionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* string action = 2; */
        if (message.action !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.action);
        /* google.protobuf.Struct args = 3; */
        if (message.args)
            Struct.internalBinaryWrite(message.args, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* int32 timeout_ms = 4; */
        if (message.timeoutMs !== 0)
            writer.tag(4, WireType.Varint).int32(message.timeoutMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.InvokeActionRequest
 */
export const InvokeActionRequest = new InvokeActionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InvokeActionResponse$Type extends MessageType<InvokeActionResponse> {
    constructor() {
        super("remote_control.home.InvokeActionResponse", [
            { no: 1, name: "ok", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "corr_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "data", kind: "message", T: () => Struct }
        ]);
    }
    create(value?: PartialMessage<InvokeActionResponse>): InvokeActionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ok = false;
        message.message = "";
        message.corrId = "";
        if (value !== undefined)
            reflectionMergePartial<InvokeActionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InvokeActionResponse): InvokeActionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool ok */ 1:
                    message.ok = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string corr_id */ 3:
                    message.corrId = reader.string();
                    break;
                case /* google.protobuf.Struct data */ 4:
                    message.data = Struct.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InvokeActionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool ok = 1; */
        if (message.ok !== false)
            writer.tag(1, WireType.Varint).bool(message.ok);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string corr_id = 3; */
        if (message.corrId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.corrId);
        /* google.protobuf.Struct data = 4; */
        if (message.data)
            Struct.internalBinaryWrite(message.data, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_control.home.InvokeActionResponse
 */
export const InvokeActionResponse = new InvokeActionResponse$Type();
/**
 * @generated ServiceType for protobuf service remote_control.home.HomeService
 */
export const HomeService = new ServiceType("remote_control.home.HomeService", [
    { name: "ListDevices", options: {}, I: ListDevicesRequest, O: ListDevicesResponse },
    { name: "WatchDevices", serverStreaming: true, options: {}, I: WatchDevicesRequest, O: DeviceEvent },
    { name: "UpsertDevice", options: {}, I: UpsertDeviceRequest, O: UpsertDeviceResponse },
    { name: "DeleteDevice", options: {}, I: DeleteDeviceRequest, O: DeleteDeviceResponse },
    { name: "InvokeAction", options: {}, I: InvokeActionRequest, O: InvokeActionResponse }
]);
