// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "home/service.proto" (package "remote_control.home", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HomeService } from "./service";
import type { InvokeActionResponse } from "./service";
import type { InvokeActionRequest } from "./service";
import type { DeleteDeviceResponse } from "./service";
import type { DeleteDeviceRequest } from "./service";
import type { UpsertDeviceResponse } from "./service";
import type { UpsertDeviceRequest } from "./service";
import type { DeviceEvent } from "./service";
import type { WatchDevicesRequest } from "./service";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListDevicesResponse } from "./service";
import type { ListDevicesRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service remote_control.home.HomeService
 */
export interface IHomeServiceClient {
    /**
     * @generated from protobuf rpc: ListDevices
     */
    listDevices(input: ListDevicesRequest, options?: RpcOptions): UnaryCall<ListDevicesRequest, ListDevicesResponse>;
    /**
     * @generated from protobuf rpc: WatchDevices
     */
    watchDevices(input: WatchDevicesRequest, options?: RpcOptions): ServerStreamingCall<WatchDevicesRequest, DeviceEvent>;
    /**
     * @generated from protobuf rpc: UpsertDevice
     */
    upsertDevice(input: UpsertDeviceRequest, options?: RpcOptions): UnaryCall<UpsertDeviceRequest, UpsertDeviceResponse>;
    /**
     * @generated from protobuf rpc: DeleteDevice
     */
    deleteDevice(input: DeleteDeviceRequest, options?: RpcOptions): UnaryCall<DeleteDeviceRequest, DeleteDeviceResponse>;
    /**
     * @generated from protobuf rpc: InvokeAction
     */
    invokeAction(input: InvokeActionRequest, options?: RpcOptions): UnaryCall<InvokeActionRequest, InvokeActionResponse>;
}
/**
 * @generated from protobuf service remote_control.home.HomeService
 */
export class HomeServiceClient implements IHomeServiceClient, ServiceInfo {
    typeName = HomeService.typeName;
    methods = HomeService.methods;
    options = HomeService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListDevices
     */
    listDevices(input: ListDevicesRequest, options?: RpcOptions): UnaryCall<ListDevicesRequest, ListDevicesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDevicesRequest, ListDevicesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WatchDevices
     */
    watchDevices(input: WatchDevicesRequest, options?: RpcOptions): ServerStreamingCall<WatchDevicesRequest, DeviceEvent> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchDevicesRequest, DeviceEvent>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpsertDevice
     */
    upsertDevice(input: UpsertDeviceRequest, options?: RpcOptions): UnaryCall<UpsertDeviceRequest, UpsertDeviceResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpsertDeviceRequest, UpsertDeviceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteDevice
     */
    deleteDevice(input: DeleteDeviceRequest, options?: RpcOptions): UnaryCall<DeleteDeviceRequest, DeleteDeviceResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteDeviceRequest, DeleteDeviceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InvokeAction
     */
    invokeAction(input: InvokeActionRequest, options?: RpcOptions): UnaryCall<InvokeActionRequest, InvokeActionResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<InvokeActionRequest, InvokeActionResponse>("unary", this._transport, method, opt, input);
    }
}
