// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: cloud/agent.proto

package cloudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	FrameType_OPEN                   FrameType = 1
	FrameType_DATA                   FrameType = 2
	FrameType_CLOSE                  FrameType = 3
	FrameType_ERROR                  FrameType = 4
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_UNSPECIFIED",
		1: "OPEN",
		2: "DATA",
		3: "CLOSE",
		4: "ERROR",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"OPEN":                   1,
		"DATA":                   2,
		"CLOSE":                  3,
		"ERROR":                  4,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_agent_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_cloud_agent_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_cloud_agent_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`               // 设备唯一ID
	HomeGrpcAddr  string                 `protobuf:"bytes,2,opt,name=home_grpc_addr,json=homeGrpcAddr,proto3" json:"home_grpc_addr,omitempty"` // 设备侧 HomeService 可达地址，例如 10.0.0.5:7071 或公网IP:端口
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`                                   // 设备注册密钥（与云端配置匹配）
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                       // 标签（可用于路由/过滤）
	TtlSec        int32                  `protobuf:"varint,5,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`                    // 注册有效期，心跳刷新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_cloud_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_cloud_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetHomeGrpcAddr() string {
	if x != nil {
		return x.HomeGrpcAddr
	}
	return ""
}

func (x *RegisterRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *RegisterRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_cloud_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_cloud_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_cloud_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_cloud_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_cloud_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_cloud_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type TunnelFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrId        string                 `protobuf:"bytes,1,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"` // 关联一次调用生命周期
	Type          FrameType              `protobuf:"varint,2,opt,name=type,proto3,enum=remote_control.cloud.v1.FrameType" json:"type,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`   // 目标方法名，仅 OPEN 时填写，例如 "/remote_control.home.HomeService/InvokeAction"
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // 负载：请求/响应/流数据按 wire 格式承载
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // 错误描述（ERROR 时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_cloud_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_cloud_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelFrame) GetCorrId() string {
	if x != nil {
		return x.CorrId
	}
	return ""
}

func (x *TunnelFrame) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_FRAME_TYPE_UNSPECIFIED
}

func (x *TunnelFrame) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TunnelFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cloud_agent_proto protoreflect.FileDescriptor

const file_cloud_agent_proto_rawDesc = "" +
	"\n" +
	"\x11cloud/agent.proto\x12\x17remote_control.cloud.v1\"\x99\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12$\n" +
	"\x0ehome_grpc_addr\x18\x02 \x01(\tR\fhomeGrpcAddr\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x17\n" +
	"\attl_sec\x18\x05 \x01(\x05R\x06ttlSec\"<\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xaa\x01\n" +
	"\vTunnelFrame\x12\x17\n" +
	"\acorr_id\x18\x01 \x01(\tR\x06corrId\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".remote_control.cloud.v1.FrameTypeR\x04type\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*Q\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\b\n" +
	"\x04DATA\x10\x02\x12\t\n" +
	"\x05CLOSE\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xd3\x01\n" +
	"\fAgentService\x12_\n" +
	"\bRegister\x12(.remote_control.cloud.v1.RegisterRequest\x1a).remote_control.cloud.v1.RegisterResponse\x12b\n" +
	"\tHeartbeat\x12).remote_control.cloud.v1.HeartbeatRequest\x1a*.remote_control.cloud.v1.HeartbeatResponse2g\n" +
	"\rTunnelService\x12V\n" +
	"\x04Open\x12$.remote_control.cloud.v1.TunnelFrame\x1a$.remote_control.cloud.v1.TunnelFrame(\x010\x01B5Z3pc-remote-ctrl/cloud-middleware/proto/cloud;cloudpbb\x06proto3"

var (
	file_cloud_agent_proto_rawDescOnce sync.Once
	file_cloud_agent_proto_rawDescData []byte
)

func file_cloud_agent_proto_rawDescGZIP() []byte {
	file_cloud_agent_proto_rawDescOnce.Do(func() {
		file_cloud_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_agent_proto_rawDesc), len(file_cloud_agent_proto_rawDesc)))
	})
	return file_cloud_agent_proto_rawDescData
}

var file_cloud_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cloud_agent_proto_goTypes = []any{
	(FrameType)(0),            // 0: remote_control.cloud.v1.FrameType
	(*RegisterRequest)(nil),   // 1: remote_control.cloud.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 2: remote_control.cloud.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: remote_control.cloud.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: remote_control.cloud.v1.HeartbeatResponse
	(*TunnelFrame)(nil),       // 5: remote_control.cloud.v1.TunnelFrame
}
var file_cloud_agent_proto_depIdxs = []int32{
	0, // 0: remote_control.cloud.v1.TunnelFrame.type:type_name -> remote_control.cloud.v1.FrameType
	1, // 1: remote_control.cloud.v1.AgentService.Register:input_type -> remote_control.cloud.v1.RegisterRequest
	3, // 2: remote_control.cloud.v1.AgentService.Heartbeat:input_type -> remote_control.cloud.v1.HeartbeatRequest
	5, // 3: remote_control.cloud.v1.TunnelService.Open:input_type -> remote_control.cloud.v1.TunnelFrame
	2, // 4: remote_control.cloud.v1.AgentService.Register:output_type -> remote_control.cloud.v1.RegisterResponse
	4, // 5: remote_control.cloud.v1.AgentService.Heartbeat:output_type -> remote_control.cloud.v1.HeartbeatResponse
	5, // 6: remote_control.cloud.v1.TunnelService.Open:output_type -> remote_control.cloud.v1.TunnelFrame
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cloud_agent_proto_init() }
func file_cloud_agent_proto_init() {
	if File_cloud_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_agent_proto_rawDesc), len(file_cloud_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cloud_agent_proto_goTypes,
		DependencyIndexes: file_cloud_agent_proto_depIdxs,
		EnumInfos:         file_cloud_agent_proto_enumTypes,
		MessageInfos:      file_cloud_agent_proto_msgTypes,
	}.Build()
	File_cloud_agent_proto = out.File
	file_cloud_agent_proto_goTypes = nil
	file_cloud_agent_proto_depIdxs = nil
}
