// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: cloud/gateway.proto

package cloudpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	home "pc-remote-ctrl/backend/proto/home"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_ListDevices_FullMethodName  = "/remote_control.cloud.v1.GatewayService/ListDevices"
	GatewayService_WatchDevices_FullMethodName = "/remote_control.cloud.v1.GatewayService/WatchDevices"
	GatewayService_UpsertDevice_FullMethodName = "/remote_control.cloud.v1.GatewayService/UpsertDevice"
	GatewayService_DeleteDevice_FullMethodName = "/remote_control.cloud.v1.GatewayService/DeleteDevice"
	GatewayService_InvokeAction_FullMethodName = "/remote_control.cloud.v1.GatewayService/InvokeAction"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 云端网关服务：前端调用此服务，由云端转发到具体设备上的 HomeService
type GatewayServiceClient interface {
	// 列出设备（转发到 HomeService）
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*home.ListDevicesResponse, error)
	// 监听设备事件（转发到 HomeService）
	WatchDevices(ctx context.Context, in *WatchDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[home.DeviceEvent], error)
	// 注册/更新设备（转发到 HomeService）
	UpsertDevice(ctx context.Context, in *UpsertDeviceRequest, opts ...grpc.CallOption) (*home.UpsertDeviceResponse, error)
	// 删除设备（转发到 HomeService）
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*home.DeleteDeviceResponse, error)
	// 调用设备动作（转发到 HomeService）
	InvokeAction(ctx context.Context, in *InvokeActionRequest, opts ...grpc.CallOption) (*home.InvokeActionResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*home.ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(home.ListDevicesResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) WatchDevices(ctx context.Context, in *WatchDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[home.DeviceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_WatchDevices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchDevicesRequest, home.DeviceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_WatchDevicesClient = grpc.ServerStreamingClient[home.DeviceEvent]

func (c *gatewayServiceClient) UpsertDevice(ctx context.Context, in *UpsertDeviceRequest, opts ...grpc.CallOption) (*home.UpsertDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(home.UpsertDeviceResponse)
	err := c.cc.Invoke(ctx, GatewayService_UpsertDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*home.DeleteDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(home.DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, GatewayService_DeleteDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) InvokeAction(ctx context.Context, in *InvokeActionRequest, opts ...grpc.CallOption) (*home.InvokeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(home.InvokeActionResponse)
	err := c.cc.Invoke(ctx, GatewayService_InvokeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// 云端网关服务：前端调用此服务，由云端转发到具体设备上的 HomeService
type GatewayServiceServer interface {
	// 列出设备（转发到 HomeService）
	ListDevices(context.Context, *ListDevicesRequest) (*home.ListDevicesResponse, error)
	// 监听设备事件（转发到 HomeService）
	WatchDevices(*WatchDevicesRequest, grpc.ServerStreamingServer[home.DeviceEvent]) error
	// 注册/更新设备（转发到 HomeService）
	UpsertDevice(context.Context, *UpsertDeviceRequest) (*home.UpsertDeviceResponse, error)
	// 删除设备（转发到 HomeService）
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*home.DeleteDeviceResponse, error)
	// 调用设备动作（转发到 HomeService）
	InvokeAction(context.Context, *InvokeActionRequest) (*home.InvokeActionResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*home.ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedGatewayServiceServer) WatchDevices(*WatchDevicesRequest, grpc.ServerStreamingServer[home.DeviceEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchDevices not implemented")
}
func (UnimplementedGatewayServiceServer) UpsertDevice(context.Context, *UpsertDeviceRequest) (*home.UpsertDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertDevice not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteDevice(context.Context, *DeleteDeviceRequest) (*home.DeleteDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedGatewayServiceServer) InvokeAction(context.Context, *InvokeActionRequest) (*home.InvokeActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeAction not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_WatchDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).WatchDevices(m, &grpc.GenericServerStream[WatchDevicesRequest, home.DeviceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_WatchDevicesServer = grpc.ServerStreamingServer[home.DeviceEvent]

func _GatewayService_UpsertDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).UpsertDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_UpsertDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).UpsertDevice(ctx, req.(*UpsertDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_InvokeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).InvokeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_InvokeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).InvokeAction(ctx, req.(*InvokeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_control.cloud.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _GatewayService_ListDevices_Handler,
		},
		{
			MethodName: "UpsertDevice",
			Handler:    _GatewayService_UpsertDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _GatewayService_DeleteDevice_Handler,
		},
		{
			MethodName: "InvokeAction",
			Handler:    _GatewayService_InvokeAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchDevices",
			Handler:       _GatewayService_WatchDevices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cloud/gateway.proto",
}
